const id='id-textbook-topik-03';
const cards=[
['berkenalan','to get acquainted (with one another)','verb','derived','neutral','kenal'],['akrab','close; familiar','adjective','root','neutral'],['melanjutkan','to continue','verb','derived','neutral','lanjut'],['pacaran','to date; be a couple','verb','derived','informal','pacar'],['menganggap','to think; consider','verb','derived','neutral','anggap'],['ketika','when','conjunction','root','neutral'],['bertemu','to meet','verb','derived','neutral','temu'],['pertemuan','meeting','noun','derived','neutral','temu'],['mengatakan','to say; state','verb','derived','formal','kata'],['makin','increasingly','adverb','root','neutral'],['meyakinkan','to convince','verb','derived','neutral','yakin'],['mampir','to drop by','verb','root','neutral'],['menunjukkan','to show; indicate','verb','derived','neutral','tunjuk'],['sikap','attitude','noun','root','neutral'],['setuju','to agree','verb','root','neutral'],['bergantung','to depend','verb','derived','neutral','gantung'],['menuruti','to follow; obey','verb','derived','neutral','turut'],['keinginan','wish; desire','noun','derived','neutral','ingin'],['membujuk','to coax; persuade','verb','derived','neutral','bujuk'],['melupakan','to forget','verb','derived','neutral','lupa'],['gelisah','restless; anxious','adjective','root','neutral'],['sendirian','alone','adverb','derived','neutral','sendiri'],['terganggu','disturbed; disrupted','adjective','derived','neutral','ganggu'],['bilang','to say','verb','root','informal']
];
const examples={'berkenalan':'Mereka berkenalan saat mengikuti kelas bahasa.','akrab':'Kedua sahabat itu sudah akrab sejak kecil.','melanjutkan':'Mereka melanjutkan percakapan setelah makan malam.','pacaran':'Mereka mulai pacaran setelah lulus sekolah.','menganggap':'Saya menganggap saran itu sangat berguna.','ketika':'Ketika hujan berhenti, kami pulang.','bertemu':'Kami bertemu di perpustakaan kemarin.','pertemuan':'Pertemuan pertama mereka berlangsung di kampus.','mengatakan':'Direktur mengatakan bahwa kantor tutup pukul lima.','makin':'Jalan itu makin ramai menjelang malam.','meyakinkan':'Petugas meyakinkan warga bahwa jembatan aman.','mampir':'Saya mampir ke rumah bibi sepulang kerja.','menunjukkan':'Pemandu menunjukkan jalan menuju museum.','sikap':'Sikapnya terhadap tetangga sangat ramah.','setuju':'Orang tua mereka setuju dengan rencana itu.','bergantung':'Jadwal kapal bergantung pada cuaca.','menuruti':'Anak itu menuruti nasihat ibunya.','keinginan':'Keinginan untuk belajar mendorongnya membaca setiap hari.','membujuk':'Ibu membujuk adik agar mau beristirahat.','melupakan':'Saya sulit melupakan pengalaman perjalanan itu.','gelisah':'Ia merasa gelisah sebelum wawancara.','sendirian':'Nenek tinggal sendirian di rumah kecil itu.','terganggu':'Konsentrasi saya terganggu oleh suara bising.','bilang':'Dalam percakapan santai, Rani bilang ia akan datang.'};
const vocabulary=cards.map(([form,meaning,pos,kind,register,root],i)=>({id:`id-t03-v${String(i+1).padStart(2,'0')}`,unitId:id,form,meaning,pos,kind,register,...(root?{root}:{}),example:examples[form]}));
const processes={'berkenalan':'ber-...-an di contoh ini menyatakan dua pihak saling mengenal; bentuk berkenalan juga dapat dibaca ber- + kenalan (“menjadi kenal”).','bertemu':'ber- membentuk verba peristiwa “bertemu”; dua orang dapat menjadi peserta tanpa objek langsung.','mengatakan':'meN-kan membentuk verba aktif “menyatakan”; klausa bahwa… menyampaikan isi yang dikatakan.'};
const morphology=[
['berkenalan','kenal',['ber-...-an'],'Maya dan Rudi berkenalan di kelas.','get acquainted with each other','Apa yang dilakukan Maya dan Rudi?',['They got acquainted.','They argued.','They moved.'],'They got acquainted.','Dalam contoh ini berkenalan menyatakan saling mengenal; bentuk ini juga dapat dianalisis sebagai ber- + kenalan.'],
['bertemu','temu',['ber-'],'Mereka bertemu setelah bekerja.','meet','Apa makna bertemu?',['meet','convince','forget'],'meet','Ber- pada bertemu membentuk verba intransitif “bertemu”.'],
['mengatakan','kata',['meN-kan'],'Agus mengatakan bahwa jadwal berubah.','say; state','Apa fungsi mengatakan?',['State information','Meet each other','Feel anxious'],'State information','Mengatakan adalah pilihan standar; bilang lebih percakapan.']
].map(([form,root,affixes,context,meaning,prompt,choices,answer,explanation],i)=>({id:`id-t03-m${i+1}`,unitId:id,form,root,affixes,context,meaning,process:processes[form],steps:[{prompt,focus:'semantic',choices,answer,explanation}]}));
export const topik03={id,bookTopic:3,title:'Apa Maunya?',level:8,description:'Ikuti cerita hubungan jarak jauh dan latih pembacaan narasi yang memakai penanda waktu.',guide:{vocabulary:'Pelajari verba pertemuan, perasaan, dan respons; perhatikan bilang informal dibanding mengatakan standar.',morphology:'Pelajari fungsi ber-...-an untuk tindakan timbal balik lewat contoh berkenalan, dengan analisis bentuk yang kontekstual.',reading:'Susun kronologi menggunakan ketika, setelah, dan lagi; bedakan peristiwa dengan perasaan tokoh.'},vocabulary,morphology,readings:[{id:'id-t03-r1',unitId:id,title:'Pesan yang tertunda',text:'Nisa berkenalan dengan Lela saat mengikuti kelas daring. Mereka segera akrab dan sering bertukar pesan. Setelah beberapa bulan, Lela pindah ke kota lain. Mereka tetap berhubungan, tetapi jadwal kerja yang berbeda membuat percakapan mereka makin jarang. Nisa lalu mengusulkan waktu khusus untuk menelepon setiap Minggu.',translation:'Nisa got acquainted with Lela while taking an online class. They quickly became close and often exchanged messages. After a few months, Lela moved to another city. They stayed in touch, but different work schedules made their conversations increasingly rare. Nisa then suggested a special time to call every Sunday.',questions:[{id:'id-t03-q1',unitId:id,prompt:'Di mana Nisa berkenalan dengan Lela?',choices:['Dalam kelas daring.','Di kantor baru.','Di rumah sakit.'],answer:'Dalam kelas daring.',explanation:'Kalimat pertama menyebut kelas daring.'},{id:'id-t03-q2',unitId:id,prompt:'Apa usul Nisa?',choices:['Waktu khusus untuk menelepon tiap Minggu.','Berhenti bertukar pesan.','Pindah kembali ke kota lama.'],answer:'Waktu khusus untuk menelepon tiap Minggu.',explanation:'Usul tersebut ada pada kalimat terakhir.'}]}]};
