const id='id-textbook-topik-02';
const cards=[
['karyawati','female employee','noun','derived','neutral','karya'],['perusahaan','company','noun','derived','neutral','usaha'],['memiliki','to have; possess','verb','derived','neutral','milik'],['kesempatan','opportunity','noun','derived','neutral','sempat'],['wanita','woman; female','noun','root','neutral'],['pria','man; male','noun','root','neutral'],['meniti karier','to pursue a career','verb','derived','formal','titi'],['karier','career','noun','root','neutral'],['sreg','right; comfortable with','adjective','root','informal'],['saat ini','currently; at this time','adverb','root','neutral'],['tawaran','offer','noun','derived','neutral','tawar'],['atasan','superior; boss','noun','derived','neutral','atas'],['menempati','to occupy; take (a position)','verb','derived','neutral','tempat'],['posisi','position','noun','root','neutral'],['namun','however','conjunction','root','formal'],['bersalah','to feel guilty','adjective','derived','neutral','salah'],['terhadap','toward; regarding','preposition','derived','formal','hadap'],['membagi','to divide','verb','derived','neutral','bagi'],['lembur','overtime; work overtime','verb','root','neutral'],['bingung','confused','adjective','root','neutral'],['melakukan','to do; carry out','verb','derived','neutral','laku'],['waktu','time','noun','root','neutral'],['kepala divisi','division head','noun','root','neutral'],['sulit','difficult','adjective','root','neutral']
];
const examples={'karyawati':'Karyawati itu memimpin rapat pagi.','perusahaan':'Perusahaan membuka kantor baru di Bandung.','memiliki':'Dina memiliki pengalaman kerja lima tahun.','kesempatan':'Semua peserta mendapat kesempatan untuk bertanya.','wanita':'Wanita itu bekerja sebagai dokter.','pria':'Pria tersebut mengantar anaknya ke sekolah.','meniti karier':'Ia meniti karier di bidang pendidikan.','karier':'Keluarganya mendukung pilihan kariernya.','sreg':'Saya kurang sreg dengan jadwal rapat malam.','saat ini':'Saat ini, kantor sedang mencari pegawai baru.','tawaran':'Mira menerima tawaran untuk pindah divisi.','atasan':'Atasan saya mengundang tim untuk berdiskusi.','menempati':'Rudi menempati posisi kepala cabang.','posisi':'Posisi itu memerlukan pengalaman mengajar.','namun':'Ia tertarik, namun masih ingin berdiskusi.','bersalah':'Saya merasa bersalah karena terlambat memberi kabar.','terhadap':'Ia bersikap terbuka terhadap saran rekan kerja.','membagi':'Dina membagi waktunya antara kantor dan keluarga.','lembur':'Tim itu lembur untuk menyelesaikan laporan.','bingung':'Saya bingung memilih jadwal yang sesuai.','melakukan':'Mereka melakukan wawancara pada hari Senin.','waktu':'Kami punya waktu untuk makan bersama.','kepala divisi':'Kepala divisi memimpin rapat bulanan.','sulit':'Tidak sulit menghubungi kantor itu.'};
const vocabulary=cards.map(([form,meaning,pos,kind,register,root],i)=>({id:`id-t02-v${String(i+1).padStart(2,'0')}`,unitId:id,form,meaning,pos,kind,register,...(root?{root}:{}),example:examples[form]}));
const processes={'memiliki':'meN-i membentuk verba aktif “mempunyai”; kesempatan berperan sebagai objek yang dimiliki.','menempati':'meN-i membentuk verba aktif “mengisi/menduduki”; posisi menjadi objek yang ditempati.','bersalah':'ber- membentuk keadaan atau sikap “berada dalam kesalahan/merasa bersalah” dari salah.'};
const morphology=[
['memiliki','milik',['meN-i'],'Kesempatan yang saya miliki cukup baik.','have; possess','Apa arti saya miliki dalam kalimat ini?',['I have','I divide','I occupy'],'I have','Bentuk meN-i di sini menyatakan mempunyai kesempatan.'],
['menempati','tempat',['meN-i'],'Ia menempati posisi yang lebih tinggi.','occupy; take a position','Apa yang ia lakukan?',['Takes a position','Feels guilty','Works overtime'],'Takes a position','Menempati adalah verba aktif berobjek: posisi.'],
['bersalah','salah',['ber-'],'Ia merasa bersalah kepada keluarga.','feel guilty','Apa yang dirasakan?',['Guilty','Confused','Promoted'],'Guilty','Dalam konteks ini bersalah menyatakan keadaan/perasaan bersalah.']
].map(([form,root,affixes,context,meaning,prompt,choices,answer,explanation],i)=>({id:`id-t02-m${i+1}`,unitId:id,form,root,affixes,context,meaning,process:processes[form],steps:[{prompt,focus:'semantic',choices,answer,explanation}]}));
export const topik02={id,bookTopic:2,title:'Merasa Bersalah',level:7,description:'Pahami surat tentang karier dan keluarga sambil membaca ungkapan opini dan pilihan formal.',guide:{vocabulary:'Bangun kosakata pekerjaan dan perasaan; bandingkan namun yang formal dengan tapi yang lebih percakapan.',morphology:'Kenali meN-i pada memiliki dan menempati serta ber- pada bersalah berdasarkan makna dalam kalimat.',reading:'Cari tawaran, kekhawatiran, lalu alasan. Baca klausa yang memakai yang secara perlahan.'},vocabulary,morphology,readings:[{id:'id-t02-r1',unitId:id,title:'Pilihan Dina',text:'Dina bekerja di sebuah perusahaan keluarga. Atasannya menawarkan posisi yang lebih tinggi. Ia tertarik, namun khawatir waktu untuk anaknya akan berkurang karena mungkin harus lembur. Dina ingin membicarakan jadwal baru itu dengan keluarganya sebelum menjawab.',translation:'Dina works at a family company. Her supervisor offers her a higher position. She is interested, but worries that time for her child will decrease because she may have to work overtime. Dina wants to discuss the new schedule with her family before answering.',questions:[{id:'id-t02-q1',unitId:id,prompt:'Mengapa Dina khawatir?',choices:['Waktu untuk anaknya mungkin berkurang.','Ia tidak memiliki pekerjaan.','Keluarganya pindah perusahaan.'],answer:'Waktu untuk anaknya mungkin berkurang.',explanation:'Teks menyebut kekhawatiran Dina tentang waktu bersama anaknya.'},{id:'id-t02-q2',unitId:id,prompt:'Apa yang ingin dilakukan Dina sebelum menjawab?',choices:['Membicarakan jadwal dengan keluarga.','Langsung menerima tawaran.','Mengundurkan diri.'],answer:'Membicarakan jadwal dengan keluarga.',explanation:'Kalimat terakhir menjelaskan rencana Dina.'}]}]};
