const id = 'id-textbook-topik-01';
const cards = [
['lambung','stomach','noun','root','neutral'],['tenggorokan','throat','noun','root','neutral'],['jantung','heart','noun','root','neutral'],['usus','intestines','noun','root','neutral'],['paru-paru','lungs','noun','root','neutral'],['ginjal','kidney','noun','root','neutral'],['lidah','tongue','noun','root','neutral'],['teratur','regular; regularly','adjective','root','neutral'],['porsi','portion','noun','root','neutral'],['secukupnya','in sufficient amount','adverb','derived','neutral','cukup'],['jadwal','schedule','noun','root','neutral'],['bioritme','biorhythm','noun','root','neutral'],['asam lambung','gastric acid','noun','root','neutral'],['kafein','caffeine','noun','root','neutral'],['mengonsumsi','to consume','verb','derived','formal','konsumsi'],['merangsang','to stimulate','verb','derived','neutral','rangsang'],['sambal','chili condiment','noun','root','neutral'],['pedas','spicy','adjective','root','neutral'],['menghindari','to avoid','verb','derived','neutral','hindar'],['menjaga','to look after; maintain','verb','derived','neutral','jaga'],['langkah','step; measure','noun','root','neutral'],['terisi','filled','adjective','derived','neutral','isi'],['makanan kecil','snack','noun','root','neutral'],['dan sebagainya','and so on','particle','root','neutral']
];
const examples={'lambung':'Dokter menjelaskan bahwa lambung mencerna makanan.','tenggorokan':'Udara melewati tenggorokan sebelum masuk ke paru-paru.','jantung':'Jantung memompa darah ke seluruh tubuh.','usus':'Usus membantu tubuh menyerap zat gizi.','paru-paru':'Paru-paru membantu kita bernapas.','ginjal':'Ginjal menyaring zat sisa dari darah.','lidah':'Lidah membantu kita merasakan makanan.','teratur':'Ia makan pada waktu yang teratur.','porsi':'Ibu mengambil porsi nasi secukupnya.','secukupnya':'Tambahkan garam secukupnya.','jadwal':'Saya mencatat jadwal makan di kalender.','bioritme':'Tidur cukup membantu menjaga bioritme tubuh.','asam lambung':'Makanan pedas dapat memicu produksi asam lambung.','kafein':'Teh dan kopi mengandung kafein.','mengonsumsi':'Ia mengonsumsi buah setiap pagi.','merangsang':'Aroma kopi merangsang selera makan.','sambal':'Ayah menambahkan sambal ke dalam sup.','pedas':'Sup itu terlalu pedas bagi adik.','menghindari':'Rina menghindari kopi sebelum tidur.','menjaga':'Olahraga membantu menjaga kesehatan jantung.','langkah':'Langkah pertama adalah makan teratur.','terisi':'Perutnya terasa terisi setelah makan siang.','makanan kecil':'Kami makan makanan kecil pada pukul empat.','dan sebagainya':'Ia membeli apel, jeruk, pisang, dan sebagainya.'};
const vocab = cards.map(([form,meaning,pos,kind,register,root],i)=>({id:`id-t01-v${String(i+1).padStart(2,'0')}`,unitId:id,form,meaning,pos,kind,register,...(root?{root}:{}),example:examples[form]}));
const processes={'menjaga':'meN- membentuk verba aktif dari jaga; objek kesehatan menjadi hal yang dipelihara.','menghindari':'meN-i membentuk verba aktif yang mengambil objek yang dijauhi, yaitu minuman berkafein.','terisi':'ter- membentuk keadaan hasil “dalam keadaan terisi”; pelaku pengisian tidak dinyatakan.'};
const morph = [
['menjaga','jaga',['meN-'],'Saya menjaga jadwal makan.','look after; maintain','Bagaimana arti menjaga dalam kalimat ini?',['maintain','avoid','fill'],'maintain','MeN- pada menjaga membentuk verba aktif dari jaga.'],
['menghindari','hindar',['meN-i'],'Ia menghindari minuman berkafein.','avoid','Apa makna menghindari?',['avoid','consume','stimulate'],'avoid','Menghindari menyatakan upaya menjauh dari sesuatu.'],
['terisi','isi',['ter-'],'Perut terasa terisi setelah makan.','be filled','Apa yang terjadi pada perut?',['It is filled.','It is avoided.','It is stimulated.'],'It is filled.','Terisi menggambarkan keadaan hasil; konteksnya tidak menyatakan siapa yang mengisi.']
].map(([form,root,affixes,context,meaning,prompt,choices,answer,explanation],i)=>({id:`id-t01-m${i+1}`,unitId:id,form,root,affixes,context,meaning,process:processes[form],steps:[{prompt,focus:'semantic',choices,answer,explanation}]}));
export const topik01={id,bookTopic:1,title:'Tips Kesehatan',level:6,description:'Baca tips pola makan dan bangun kosakata formal sederhana tentang tubuh serta kesehatan.',guide:{vocabulary:'Pelajari nama organ dan kata untuk jadwal makan; bedakan bentuk dasar dari verba berimbuhan.',morphology:'Amati meN- dalam verba aktif, meN-i pada menghindari, serta ter- yang menandai keadaan hasil pada terisi.',reading:'Mulai dari petunjuk kesehatan pendek. Tandai saran, alasan, dan akibat yang dihubungkan dengan sehingga.'},vocabulary:vocab,morphology:morph,grammar:[{"id": "id-t01-grammar-1", "unitId": "id-textbook-topik-01", "context": "Imperatif: Kamu harus menghindari kopi sebelum tidur. Pilih bentuk perintah yang tepat.", "prompt": "Bagaimana menulis nasihat langsung tanpa subjek?", "choices": ["Hindari kopi sebelum tidur!", "Menghindari kopi sebelum tidur!", "Dihindari kopi sebelum tidur!"], "answer": "Hindari kopi sebelum tidur!", "explanation": "Imperatif verba transitif menghilangkan awalan meN-; akhiran -lah boleh dipakai untuk memperhalus."},{"id": "id-t01-grammar-2", "unitId": "id-textbook-topik-01", "context": "Dasar: tulis. Konteks: Anda meminta seseorang menulis nomor telepon dengan sopan.", "prompt": "Bentuk perintah mana yang sesuai?", "choices": ["Tulislah nomor telepon Anda.", "Menulislah nomor telepon Anda.", "Ditulislah nomor telepon Anda."], "answer": "Tulislah nomor telepon Anda.", "explanation": "Imperatif memakai dasar tulis; -lah dapat memperhalus perintah."},{"id": "id-t01-grammar-3", "unitId": "id-textbook-topik-01", "context": "Konteks: “Bau asap itu ___ saya.” Maksudnya: membuat saya merasa takut.", "prompt": "Pilih bentuk yang berfungsi sebagai predikat adjektival penyebab perasaan.", "choices": ["menakutkan", "menakuti", "takut"], "answer": "menakutkan", "explanation": "Menakutkan dapat berfungsi sebagai adjektiva “frightening”; menakuti berarti menimbulkan rasa takut pada objek."}], readings:[{id:'id-t01-r1',unitId:id,title:'Jadwal makan Rani',text:'Rani sering melewatkan sarapan. Perawat menyarankan tiga waktu makan yang teratur dan porsi secukupnya. Rani juga menghindari kopi pada malam hari. Setelah dua minggu, lambungnya terasa lebih nyaman.',translation:'Rani often skips breakfast. The nurse recommends three regular meal times and sufficient portions. Rani also avoids coffee at night. After two weeks, her stomach feels more comfortable.',questions:[{id:'id-t01-q1',unitId:id,prompt:'Apa saran perawat?',choices:['Makan teratur dengan porsi cukup.','Minum kopi pada malam hari.','Melewatkan semua waktu makan.'],answer:'Makan teratur dengan porsi cukup.',explanation:'Kalimat kedua menyebut tiga waktu makan teratur dan porsi secukupnya.'},{id:'id-t01-q2',unitId:id,prompt:'Apa yang Rani hindari pada malam hari?',choices:['Kopi.','Sarapan.','Air putih.'],answer:'Kopi.',explanation:'Teks menyatakan Rani menghindari kopi pada malam hari.'}]}]};
