// Decomposes a morphology card's canonical answer (e.g. "first aorist active
// indicative second person plural") into an ordered sequence of single-
// dimension multiple-choice steps for the step-by-step parsing drill.
//
// Dimension ordering, fixed:
//   verbs:    tense → voice → mood → person → number   (+ case/number/gender
//             tail for participles, no person)
//   nominals: case → number → gender
//
// Wrong picks reveal the correct dimension answer, then advance.

// Master pool of choices per dimension. The decomposer derives the correct
// answer from the card's parsed answer string and pulls distractors from the
// remaining pool entries for that dimension.
const DIM_POOLS = {
  aspect: ['continuous', 'undefined', 'continuous/undefined', 'completed'],
  tense:  ['present', 'future', 'imperfect', 'aorist', 'first aorist', 'second aorist', 'perfect', 'pluperfect'],
  voice:  ['active', 'middle', 'passive', 'middle/passive'],
  mood:   ['indicative', 'subjunctive', 'optative', 'imperative', 'infinitive', 'participle'],
  person: ['first', 'second', 'third'],
  case:   ['nominative', 'accusative', 'genitive', 'dative', 'vocative'],
  number: ['singular', 'plural'],
  gender: ['masculine', 'feminine', 'neuter']
};

const DIM_LABEL = {
  aspect: 'Aspect',
  tense:  'Tense',
  voice:  'Voice',
  mood:   'Mood',
  person: 'Person',
  case:   'Case',
  number: 'Number',
  gender: 'Gender'
};

// Display order for MC choice lists (sortChoicesCanonically). Extends the bare
// DIM_POOLS singles with the syncretic/composite values, keeping each combined
// option (the neuter "nominative/accusative", a 2-termination adjective's
// "masculine/feminine") next to a component it combines instead of exiling it
// to the end of the list where it's easy to overlook and skip past. Case uses
// a deliberate teaching order (nominative, nominative/accusative, vocative,
// accusative, genitive, dative) rather than strict alphabetical. This only
// affects ORDERING, never which choices appear (that's buildChoices) —
// composites still surface only when they're the actual syncretic answer, not
// as distractors. Dimensions without an entry here fall back to DIM_POOLS order.
const CHOICE_SORT_ORDER = {
  case:   ['nominative', 'nominative/accusative', 'vocative', 'accusative', 'genitive', 'dative'],
  gender: ['masculine', 'feminine', 'neuter', 'masculine/feminine', 'masculine/neuter', 'masculine/feminine/neuter']
};

// Aspect is implicit in tense in Duff's pedagogy. Present and future are
// genuinely ambiguous between continuous (imperfective) and undefined
// (aoristic) — the form alone doesn't pick one (progressive vs gnomic for
// the present; context decides for the future), so the right parse is the
// composite 'continuous/undefined'. Imperfect commits to continuous,
// aorist to undefined, perfect/pluperfect to completed. Exactly one
// correct aspect per tense; picking just one half of the composite for
// present/future overcommits and is marked wrong.
const TENSE_TO_ASPECT = {
  'present':       'continuous/undefined',
  'imperfect':     'continuous',
  'future':        'continuous/undefined',
  'aorist':        'undefined',
  'first aorist':  'undefined',
  'second aorist': 'undefined',
  'perfect':       'completed',
  'pluperfect':    'completed'
};

export function aspectForTense(tense) {
  return TENSE_TO_ASPECT[tense] || '';
}

// When the student gets the aspect step wrong, returns a short clarifying
// note explaining the mistake. Especially important when the picked value
// visually overlaps the correct one (e.g. picking "continuous" when the
// correct is "continuous/undefined") — the strikethrough alone reads like
// a close miss rather than a real error, so an explicit note disambiguates.
// Returns '' when no special note is warranted (e.g. picking "continuous"
// for an aorist; the standard "continuous → undefined" line is clear).
export function aspectMistakeNote(tense, picked, correct) {
  if (!tense || !picked || picked === correct) return '';
  if (correct === 'continuous/undefined') {
    return `${tense} is aspectually ambiguous — pick continuous/undefined, not just ${picked}`;
  }
  if (picked === 'continuous/undefined') {
    return `${tense} isn't ambiguous — it commits to ${correct}`;
  }
  return '';
}

const DIM_DISPLAY_SUFFIX = {
  person: ' person'
};

function findToken(text, regex) {
  if (!text) return '';
  const match = String(text).match(regex);
  return match ? match[0].toLowerCase() : '';
}

// Parse a canonical answer like "aorist active indicative first person plural"
// or "nominative singular masculine" into { tense, voice, mood, person, case,
// number, gender }, with missing dimensions left as ''.
//
// The parser accepts both the canonical long-form (auto-generated by
// paradigm_morphology.js — "first person plural", "masculine") and the
// abbreviated short-form used throughout hand-written grammar.js cards
// ("1st pl.", "masc."). Lookaheads on person prevent "1st aorist" /
// "2nd declension" from false-positiving as person markers.
const CASE_ABBREVS = { 'nom.': 'nominative', 'acc.': 'accusative', 'gen.': 'genitive', 'dat.': 'dative', 'voc.': 'vocative' };
const GENDER_ABBREVS = { 'masc.': 'masculine', 'fem.': 'feminine', 'neut.': 'neuter' };
const PERSON_WORDS = { '1st': 'first', '2nd': 'second', '3rd': 'third', first: 'first', second: 'second', third: 'third' };

function expandComposite(text, abbrevMap, canonicalList) {
  // Matches a slash-composite of either full canonical words ("nominative/
  // accusative") or matching short-forms ("nom./acc."). Returns the slash
  // composite in canonical form, or '' when nothing matches.
  const full = canonicalList.join('|');
  const fullRe = new RegExp(`\\b(${full})(?:\\/(?:${full}))*\\b`);
  const fullMatch = text.match(fullRe);
  if (fullMatch) return fullMatch[0];
  const shortKeys = Object.keys(abbrevMap).map(k => k.replace(/\./g, '\\.'));
  const short = shortKeys.join('|');
  const shortRe = new RegExp(`(${short})(?:\\/(?:${short}))*`);
  const shortMatch = text.match(shortRe);
  if (!shortMatch) return '';
  return shortMatch[0]
    .split('/')
    .map(piece => abbrevMap[piece] || piece)
    .join('/');
}

export function parseAnswerDimensions(answer) {
  const a = String(answer || '').toLowerCase();
  const cleaned = a.replace(/[(),;]/g, ' ').replace(/\s+/g, ' ').trim();

  const qualifierTense = findToken(cleaned, /\b(first aorist|second aorist)\b/);
  const tense = qualifierTense
    || findToken(cleaned, /\b(present|future|imperfect|aorist|perfect|pluperfect)\b/);
  const voice = findToken(cleaned, /\b(middle\/passive|middle or passive|active|middle|passive)\b/)
    .replace(/middle or passive/, 'middle/passive');
  const mood = findToken(cleaned, /\b(indicative|subjunctive|optative|imperative|infinitive|participle)\b/);
  let person = findToken(cleaned, /\b(first|second|third) person\b/).replace(/\s+person$/, '');
  if (!person) {
    const abbrev = cleaned.match(/\b(1st|2nd|3rd|first|second|third)\b(?=\s+(?:sg\.?|pl\.?|singular|plural)\b)/);
    if (abbrev) person = PERSON_WORDS[abbrev[1]] || '';
  }
  const number = findToken(cleaned, /\b(singular|plural)\b/)
    || (/\bsg\.?\b/.test(cleaned) ? 'singular' : /\bpl\.?\b/.test(cleaned) ? 'plural' : '');

  // Case can be syncretic ("nominative/accusative" or "nom./acc.").
  const grammaticalCase = expandComposite(cleaned, CASE_ABBREVS, ['nominative', 'accusative', 'genitive', 'dative', 'vocative']);

  // Gender can be combined ("all genders" / "masculine/feminine/neuter" /
  // "masc./neut."). Canonicalize tri-gender to the splittable composite so
  // dimsCompatible can match it against a specific gender pick.
  const allGenders = /\ball genders?\b/.test(cleaned) || /\bmasculine\/feminine\/neuter\b/.test(cleaned) || /masc\.\/fem\.\/neut\./.test(cleaned);
  const gender = allGenders
    ? 'masculine/feminine/neuter'
    : expandComposite(cleaned, GENDER_ABBREVS, ['masculine', 'feminine', 'neuter']);

  // Aspect is derived from tense (Duff's pedagogy: aspect is the primary
  // category, with tense as a secondary marker). Missing tense → no aspect.
  const aspect = tense ? aspectForTense(tense) : '';

  return { aspect, tense, voice, mood, person, case: grammaticalCase, number, gender };
}

// Stable canonical ordering for parsing-mode MC option lists. Items present
// in the dimension's order (CHOICE_SORT_ORDER, else DIM_POOLS) keep that
// pedagogical order (present → future → imperfect → aorist → …; nom → acc →
// nom/acc → gen → dat → voc; masc → fem → neut → masc/fem → masc/neut →
// masc/fem/neut). Any value still not listed (an unforeseen composite) sorts
// last, alphabetically among such values. Used instead of random shuffling so
// the same dimension always presents its choices in the same order
// card-to-card — random reordering forced re-reading on every step and broke
// the muscle-memory mapping between paradigm-table position and option slot.
function sortChoicesCanonically(dimensionKey, values) {
  const canonical = CHOICE_SORT_ORDER[dimensionKey] || DIM_POOLS[dimensionKey] || [];
  const ord = (v) => {
    const i = canonical.indexOf(v);
    return i === -1 ? canonical.length : i;
  };
  return [...values].sort((a, b) => {
    const oa = ord(a);
    const ob = ord(b);
    if (oa !== ob) return oa - ob;
    return String(a).localeCompare(String(b));
  });
}

// True iff the given dim value should be visible / included given the
// user's per-value filter map. Composite values (e.g. 'continuous/undefined',
// 'middle/passive') pass when at least one slash-component is enabled;
// aorist qualifiers ('first aorist' / 'second aorist') normalize to 'aorist'
// for the lookup. A missing filter map (or missing dim entry) is treated as
// "everything enabled" so the existing default-on behavior survives.
export function dimValuePassesFilter(dimensionKey, value, dimValueFilters) {
  if (!value || !dimValueFilters || typeof dimValueFilters !== 'object') return true;
  const sub = dimValueFilters[dimensionKey];
  if (!sub || typeof sub !== 'object') return true;
  const normalized = String(value).replace(/^(first |second )/, '');
  const parts = normalized.split('/');
  return parts.some((p) => sub[p] !== false);
}

function buildChoices(dimensionKey, correct, accessiblePool, dimValueFilters) {
  // Prefer the chapter-gated accessible pool when provided (only values that
  // appear in morph cards the student has access to at their current point in
  // the course). Fall back to the full DIM_POOLS list if no pool was passed —
  // useful for unit tests and for callers that don't gate.
  //
  // The full accessible pool is shown — every distinct value the student has
  // learned for this dimension to date — rather than a 4-choice cap. As the
  // course progresses the choice list grows, mirroring expanding paradigm
  // recognition.
  //
  // Per-value filters prune distractors the user has opted out of — but the
  // `correct` value is always kept regardless, so a step never becomes
  // unanswerable just because the user disabled that value as a distractor.
  const sourcePool = accessiblePool && accessiblePool.length
    ? accessiblePool
    : (DIM_POOLS[dimensionKey] || []);
  const seen = new Set([correct]);
  const all = [correct];
  for (const candidate of sourcePool) {
    if (seen.has(candidate)) continue;
    if (!dimValuePassesFilter(dimensionKey, candidate, dimValueFilters)) continue;
    seen.add(candidate);
    all.push(candidate);
  }
  return sortChoicesCanonically(dimensionKey, all);
}

// Walks a set of morph cards (e.g. every card whose source chapter is ≤ the
// student's max selected chapter) and returns the unique values that appear
// in each parsing dimension. Used to build chapter-gated MC distractor pools
// so the drill never asks about a tense/mood/case the textbook hasn't yet
// introduced. Person/number/voice/gender are conceptually foundational and
// have small fixed pools, so they're seeded with their full standard sets
// whenever a verb/nominal card is in scope — otherwise a card tagged with
// (say) voice=middle alone would render a single-choice voice step.
export function computeAccessibleDimensionPools(cards) {
  const pools = {
    aspect: new Set(), tense: new Set(), voice: new Set(), mood: new Set(), person: new Set(),
    case: new Set(), number: new Set(), gender: new Set()
  };
  let sawVerb = false;
  let sawNominal = false;
  (cards || []).forEach((card) => {
    if (!card || !(card.parsedAnswer || card.answer)) return;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
    // First/second aorist aren't separate tenses — they're the aorist tense
    // with a first/weak (ἔλυσα) vs second/strong (ἔλιπον) stem formation, a
    // lexical property rather than a parse dimension. Collapse the qualifier
    // so the Tense step's distractor pool only ever holds the six base tenses
    // and never offers "first aorist"/"second aorist" beside "aorist".
    if (dims.tense) dims.tense = dims.tense.replace(/^(first |second )/, '');
    Object.keys(pools).forEach((k) => {
      if (dims[k]) pools[k].add(dims[k]);
    });
    if (dims.tense || dims.voice || dims.person) sawVerb = true;
    if (dims.case || dims.gender) sawNominal = true;
    // Aspect pool: continuous, undefined, and the composite continuous/undefined
    // are foundational from the present onward, so always expose all three
    // as choices — the student needs to distinguish "either reading is valid"
    // from "this form commits to one reading" on every card. The composite is
    // never auto-correct from being present in the choices: it's only right
    // for present/future. 'completed' arrives via the per-card add above
    // when a perfect-stem form is in the accessible set.
    if (dims.tense) {
      pools.aspect.add('continuous');
      pools.aspect.add('undefined');
      pools.aspect.add('continuous/undefined');
    }
  });
  if (sawVerb) {
    ['first', 'second', 'third'].forEach(p => pools.person.add(p));
    ['singular', 'plural'].forEach(n => pools.number.add(n));
    // Voice is intentionally NOT seeded as a whole — it stays whatever
    // the accessible cards have tagged. Duff doesn't introduce voice
    // formally until ch 15 (with deponent verbs covered ch 8/9 as the
    // bridge), so seeding all four voices would show "active vs
    // middle/passive" choices to chapter 5 students who only have
    // active forms in scope. Letting the pool grow organically means
    // chapters that haven't yet introduced voice see no voice
    // distractors; buildMorphSteps additionally skips the voice step
    // entirely for active-tagged cards before ch 15.
    //
    // BUT: once any non-active voice has shown up (chapter 8/9 onward
    // with deponents), seed 'active' as the comparison voice so the
    // deponent's middle/passive voice step doesn't render as a
    // single-choice no-info pick.
    const sawNonActiveVoice = [...pools.voice].some(v => v && v !== 'active');
    if (sawNonActiveVoice) pools.voice.add('active');
  }
  if (sawNominal) {
    ['singular', 'plural'].forEach(n => pools.number.add(n));
    ['masculine', 'feminine', 'neuter'].forEach(g => pools.gender.add(g));
  }
  const out = {};
  Object.keys(pools).forEach((k) => { out[k] = [...pools[k]]; });
  return out;
}

function applyDisplaySuffix(dimensionKey, value) {
  const suffix = DIM_DISPLAY_SUFFIX[dimensionKey];
  return suffix ? `${value}${suffix}` : value;
}

// 2nd-person plural present (any voice) is genuinely syncretic in Koine
// Greek: the indicative and imperative are spelt the same — λύετε is both
// "you (pl.) are untying" and "untie!"; likewise λύεσθε for the middle/
// passive. The form alone doesn't pick one mood; only context (presence
// of a subject, surrounding clauses) decides. When a card's parse names
// this configuration we accept either mood at the Mood step, instead of
// marking the alternate reading wrong.
//
// Detected from the raw answer text so this works across canonical
// ("second person plural") and abbreviated ("2nd pl.") formats. Imperative
// cards may omit person entirely (structurally 2nd) — treated as 2nd-pl
// when the only number marker is plural and no 1st/3rd person tag appears.
export function isSecondPluralPresentMoodAmbiguity(answer, parsedDims) {
  if (!answer) return false;
  const dims = parsedDims || parseAnswerDimensions(answer);
  if (dims.tense !== 'present') return false;
  if (dims.mood !== 'indicative' && dims.mood !== 'imperative') return false;
  const a = String(answer).toLowerCase();
  const isPlural = dims.number === 'plural' || /\bplural\b/.test(a) || /\bpl\./.test(a);
  if (!isPlural) return false;
  if (dims.person === 'second') return true;
  if (/\b2nd\b/.test(a) || /\bsecond person\b/.test(a)) return true;
  // Imperative cards are structurally 2nd person and often omit person
  // markers entirely. Treat as 2nd plural when no other person is named.
  if (dims.mood === 'imperative' && !dims.person
      && !/\b(1st|3rd|first person|third person)\b/.test(a)) {
    return true;
  }
  return false;
}

// Short "how to tell it apart" hints for forms that are easy to confuse with a
// neighbouring parse. Triggered off the parsed dimensions (reliable) and worded
// to stay true across the regular ω-verb, contract, μι-, and deponent
// paradigms the drill covers — each hint names the exception where the simple
// rule breaks (liquid futures, 2nd-aorist passives) rather than overclaiming.
// Shown in the forward (Greek → English) walk summary, alongside the
// ambiguous-imperative note. Returns [] when nothing applies.
//
// Kept to patterns whose distinguishing marker is genuinely systematic:
// present↔future σ, the past-indicative augment (+ the imperfect ‑ον 1sg/3pl
// syncretism), the aorist-passive ‑θη‑, perfect/pluperfect reduplication, the
// participle suffix/declension tells, and the infinitive endings. (The aorist's
// ‑σα‑ is intentionally NOT hinted — κ-aorists ἔδωκα, 2nd aorists, and liquid
// aorists ἔμεινα all break it.)
export function confusableFormHints(answer, parsedDims, form) {
  const dims = parsedDims || parseAnswerDimensions(answer || '');
  if (!dims) return [];
  const { tense, voice, mood } = dims;
  const isMiddlePassive = voice === 'middle' || voice === 'passive' || voice === 'middle/passive';
  const formNfc = form ? String(form).normalize('NFC').trim() : '';
  const hints = [];
  // Present ↔ future: the tense-forming σ — the single most-confused contrast
  // in the regular paradigm (λύει vs λύσει). Holds for active and
  // middle/passive; the 2 pl. m/p is the cleanest tell (one σ vs two).
  if ((tense === 'present' || tense === 'future') && mood === 'indicative') {
    hints.push(isMiddlePassive
      ? 'Present vs future middle/passive: the future slots a σ before the ending — λύομαι → λύσομαι, and 2 pl. λύεσθε (one σ) → λύσεσθε (two σ). Liquid/nasal stems (μένω, κρίνω) hide the σ and contract instead: μενοῦμαι.'
      : 'Present vs future active: the future slots a σ between stem and ending — λύω → λύσω, λύει → λύσει. Liquid/nasal stems (μένω, κρίνω) hide the σ and contract instead: μενῶ.');
  }
  // Augment = a past-tense indicative. Imperfect, aorist, and pluperfect
  // indicatives all carry an augment; it appears ONLY in the indicative, so it
  // cleanly separates e.g. the aorist indicative ἔλυσα from the augmentless
  // aorist subjunctive λύσω / infinitive λῦσαι / participle λύσας, and the
  // imperfect from the present. (Perfect is excluded — it reduplicates instead
  // of augmenting.)
  const isPastIndicative = mood === 'indicative'
    && (tense === 'imperfect' || tense === 'aorist' || tense === 'first aorist'
        || tense === 'second aorist' || tense === 'pluperfect');
  if (isPastIndicative) {
    hints.push('Augment = a past-tense indicative: a prefixed ἐ‑/ἔ‑ (ἔλυον, ἔλυσα, ἐλύθην) or a lengthened initial vowel (ἀκούω → ἤκουον); in compounds it sits after the prefix (ἀπ‑έ‑θανον). It shows up only in the indicative — the same tense’s subjunctive, infinitive, and participle have no augment (λύσω, λῦσαι, λύσας).');
  }
  // Imperfect active ‑ον is identical in the 1 sg. and 3 pl. (ἔλυον). Flag it
  // only when the form actually shows that ending, so it never misfires on a
  // μι-verb (ἐδίδουν 1 sg. ≠ ἐδίδοσαν 3 pl.).
  if (tense === 'imperfect' && mood === 'indicative' && /ον$/.test(formNfc)) {
    hints.push('Imperfect active ‑ον is spelt the same in the 1 sg. and the 3 pl. (ἔλυον = “I was untying” or “they were untying”) — only context tells them apart.');
  }
  // Aorist passive: the ‑θη‑ infix.
  if (tense === 'aorist' && voice === 'passive') {
    hints.push('Aorist passive: the ‑θη‑ infix is the tell (ἐ‑λύ‑θη‑ν, ἐ‑λύ‑θη‑ς …). A few verbs take a bare ‑η‑ instead — the 2nd aorist passive, e.g. ἐ‑γράφ‑η‑ν.');
  }
  // Perfect / pluperfect: reduplication is the signature.
  if (tense === 'perfect' || tense === 'pluperfect') {
    hints.push('Perfect/pluperfect: the reduplication (usually the initial consonant + ε — λέ‑λυκα, λέ‑λυμαι) marks the stem, and the active usually adds a ‑κ‑ (λέλυκα). The pluperfect prefixes an augment on top (ἐ‑λελύκειν).');
  }
  // Participle: the suffix carries voice, and the declension pattern tells you
  // where case/gender live. ‑μενος is never active; the aorist passive (‑θείς)
  // is the one voice-marked participle that isn't ‑μενος.
  if (mood === 'participle') {
    hints.push('Participle voice is in the suffix: ‑μενος/‑μένη/‑μενον is middle or middle/passive (λυόμενος, λυσάμενος, λελυμένος) — never active. The aorist passive is the exception, ending ‑(θ)είς (λυθείς; a few verbs drop the θ — γραφείς). The active ‑ων/‑ας/‑ώς types and ‑θείς decline 3rd-declension in the masc./neut. and 1st-declension in the fem. (λύων, λύουσα, λῦον; gen. λύοντος, λυούσης), so case and gender show in the ending; ‑μενος types decline like a 2-1-2 adjective.');
  }
  // Infinitive endings: four shapes, three of them ending in ‑αι.
  if (mood === 'infinitive') {
    hints.push('Infinitives end in ‑ειν, ‑σαι, ‑ναι, or ‑σθαι — three of the four close in ‑αι. ‑σθαι is middle/passive (λύεσθαι); ‑ναι covers the aorist passive (λυθῆναι), perfect active (λελυκέναι), and μι-verbs/εἰμί (διδόναι, εἶναι); ‑σαι is the 1st-aorist active (λῦσαι); ‑ειν is the present/future and 2nd-aorist active (λύειν, εἰπεῖν).');
  }
  return hints;
}

// When the student picks a mood that requires more dimensions than the
// source card's parse class supplied, returns the dim keys to inject as
// ungraded follow-up steps. Example: card λῦε is a 2-singular imperative
// — its steps don't include person (the canonicalized answer drops "2nd"
// without "person"). If the student picks mood=indicative, they need to
// commit to a person before we can resolve their picks to a single Greek
// form; inject person (and number if the card also lacks one).
//
// Imperative is treated specially: Koine has no 1st-person imperative, and the
// 3rd person isn't taught until ch 17. Before then an imperative is
// structurally 2nd person, so only number is injected; from ch 17 the student
// must also commit to person (2nd vs 3rd), so person is injected too (gated on
// `options.maxChapter`).
//
// Returns [] when no injection is needed. Voice is never injected here —
// it's introduced in chapter 15 and gated separately.
const FINITE_MOODS_NEEDING_PERSON_NUMBER = new Set(['indicative', 'subjunctive', 'optative']);
export function inferredFollowupDims(stepKey, picked, existingStepKeys, options = {}) {
  if (stepKey !== 'mood' || !picked) return [];
  const have = existingStepKeys instanceof Set ? existingStepKeys : new Set(existingStepKeys || []);
  const maxChapter = Number.isFinite(options.maxChapter) ? options.maxChapter : Infinity;
  const out = [];
  if (FINITE_MOODS_NEEDING_PERSON_NUMBER.has(picked)) {
    if (!have.has('person')) out.push('person');
    if (!have.has('number')) out.push('number');
  } else if (picked === 'imperative') {
    // 2nd person before ch 17; from ch 17 the 3rd person exists too, so the
    // student must commit to a person before the form resolves.
    if (maxChapter >= THIRD_PERSON_IMPERATIVE_CHAPTER && !have.has('person')) out.push('person');
    if (!have.has('number')) out.push('number');
  } else if (picked === 'participle') {
    if (!have.has('case'))   out.push('case');
    if (!have.has('number')) out.push('number');
    if (!have.has('gender')) out.push('gender');
  }
  // infinitive: no follow-ups needed (no person/number/case/gender).
  return out;
}

// Structural impossibilities in Koine Greek that don't depend on a specific
// lemma — these are paradigm-level gaps any verb shares. Separate from the
// per-lemma negative inventory in js/data/lemma_inventory.js (which handles
// lemma-specific gaps like aorist εἰμί). When the student's picks combine
// into one of these, the form lookup should explain *why* no morph exists
// instead of just rendering "[no morph exists]".
const STRUCTURAL_TENSE_MOOD_IMPOSSIBILITIES = [
  { tense: 'future',     mood: 'imperative',  why: 'no future imperative exists' },
  { tense: 'future',     mood: 'subjunctive', why: 'no future subjunctive exists' },
  // The optative IS attested in present, future, aorist, and perfect — the
  // future optative (λυσοίμην, λύσοιμι) is the one mood that keeps a future
  // form Koine's subjunctive lacks — so there is no future-optative gap here.
  // It is barred only from the two indicative-only past tenses.
  { tense: 'imperfect',  mood: 'optative',    why: 'no imperfect optative exists (imperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'optative',    why: 'no pluperfect optative exists (pluperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'subjunctive', why: 'no imperfect subjunctive exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'imperative',  why: 'no imperfect imperative exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'infinitive',  why: 'no imperfect infinitive exists (imperfect is indicative-only)' },
  { tense: 'imperfect',  mood: 'participle',  why: 'no imperfect participle exists (imperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'subjunctive', why: 'no pluperfect subjunctive exists (pluperfect is indicative-only)' },
  { tense: 'pluperfect', mood: 'imperative',  why: 'no pluperfect imperative exists (pluperfect is indicative-only)' },
  // The perfect infinitive (λελυκέναι) and perfect participle (λελυκώς) do
  // double duty for both perfect and pluperfect aspect — Koine has no
  // distinct pluperfect non-indicative forms.
  { tense: 'pluperfect', mood: 'infinitive',  why: 'no pluperfect infinitive exists (the perfect infinitive covers both)' },
  { tense: 'pluperfect', mood: 'participle',  why: 'no pluperfect participle exists (the perfect participle covers both)' }
];

// Returns a short explanation when the picked (tense, mood) combo is
// structurally impossible in Koine, or null otherwise. Aorist qualifiers
// (first/second) are collapsed onto 'aorist' since they don't introduce
// new mood gaps.
export function structuralImpossibilityReason(pickedDims) {
  if (!pickedDims) return null;
  const tenseRaw = String(pickedDims.tense || '').toLowerCase();
  const mood = String(pickedDims.mood || '').toLowerCase();
  if (!tenseRaw || !mood) return null;
  const tense = tenseRaw.replace(/^(first |second )/, '');
  for (const entry of STRUCTURAL_TENSE_MOOD_IMPOSSIBILITIES) {
    if (entry.tense === tense && entry.mood === mood) return entry.why;
  }
  return null;
}

// ─── Paradigm-level value gaps ───────────────────────────────────────────
//
// Some paradigms own a dimension but carry only a subset of its values. The
// first/second personal pronouns (ἐγώ, σύ) inflect for person — but only
// first and second; the third-person personal pronoun is a separate paradigm
// (αὐτός, αὐτή, αὐτό). The person step still offers "third" as a distractor
// (any verb in scope seeds all three persons into the shared pool), so a
// student can pick a person the focused paradigm structurally lacks. When
// that happens there's no form to resolve and no point marching through the
// remaining dimensions — the walk should cut off and explain the gap, the
// same way structuralImpossibilityReason ends an impossible tense/mood walk.
//
// Scoped to `person` deliberately. Person is the one dimension where a
// paradigm legitimately owns the category yet lacks specific values without
// that being a chapter-gating artifact (chapter gating already prunes
// tense/mood/case distractors the textbook hasn't introduced). Nouns and
// adjectives have no person at all, so `presentValues.person` is empty for
// them and nothing is gated.
const PERSON_GLOSS = { first: 'first', second: 'second', third: 'third' };

// Curated structural gaps asserted from Greek morphology — NOT inferred from
// drilled data. Used only for gaps that present-values can't safely detect,
// because the missing value is also undrilled for paradigms that DO have it
// (e.g. most nouns never drill their vocative — λόγος has λόγε — so
// absence-in-data ≠ no-such-form). Keyed by focused-paradigm lemma → the dim
// values that genuinely don't exist for it. Kept to certain, lemma-stable
// gaps, same bar as lemma_inventory's impossible* lists.
//
// The Greek article and every pronoun inflect for the nominative, accusative,
// genitive, and dative only — they have NO vocative case. Nouns and adjectives
// DO have a vocative, so they are deliberately absent here and never gated.
const PARADIGM_STRUCTURAL_GAPS = {
  'ὁ, ἡ, τό':                           { case: ['vocative'] }, // the article
  'First and second personal pronouns': { case: ['vocative'] }, // ἐγώ / σύ
  'αὐτός, αὐτή, αὐτό':                  { case: ['vocative'] }, // intensive / 3rd-person
  'οὗτος, αὕτη, τοῦτο':                 { case: ['vocative'] }, // demonstrative "this"
  'ἐκεῖνος, ἐκείνη, ἐκεῖνο':            { case: ['vocative'] }, // demonstrative "that"
  'ὅς, ἥ, ὅ':                           { case: ['vocative'] }, // relative
  'τίς, τί':                            { case: ['vocative'] }  // interrogative / indefinite
};

// Set of values the focused paradigm actually carries per dimension, derived
// from its full (unfiltered) card pool. Composite values split so a paradigm
// tagged "first/second" registers both members. Consumed by paradigmGapReason.
export function computeParadigmPresentValues(cards) {
  const dimKeys = ['aspect', 'tense', 'voice', 'mood', 'person', 'case', 'number', 'gender'];
  const present = {};
  dimKeys.forEach((k) => { present[k] = new Set(); });
  (cards || []).forEach((card) => {
    if (!card) return;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer || '');
    dimKeys.forEach((k) => {
      if (!dims[k]) return;
      String(dims[k]).split('/').forEach((v) => { if (v) present[k].add(v); });
    });
  });
  return present;
}

// Returns { dim, picked, short, note } when the student's picks name a person
// the focused paradigm has no forms for, or null otherwise. `presentValues`
// comes from computeParadigmPresentValues over the paradigm's full pool. A
// paradigm with no person dimension (every noun/adjective) has an empty
// person set and is never gated; one that carries the picked person passes.
export function paradigmGapReason(pickedDims, presentValues, lemma) {
  if (!pickedDims || !presentValues) return null;
  // 1) Person on a person-bearing, tenseless paradigm (the 1st/2nd personal
  //    pronouns) that lacks the picked person — derived from drilled forms.
  const personGap = personGapReason(pickedDims, presentValues);
  if (personGap) return personGap;
  // 2) Curated structural gaps (currently case=vocative on the article and
  //    pronouns), asserted from morphology and guarded against the paradigm
  //    actually drilling the value.
  const curated = lemma ? PARADIGM_STRUCTURAL_GAPS[lemma] : null;
  if (curated) {
    const curatedGap = curatedGapReason(pickedDims, presentValues, curated);
    if (curatedGap) return curatedGap;
  }
  return null;
}

function personGapReason(pickedDims, presentValues) {
  const picked = pickedDims.person;
  const pool = presentValues.person;
  if (!picked || !pool || pool.size === 0) return null; // no person dim → nothing to gate
  // Only gate person for a person-bearing paradigm that is NOT a verb — i.e.
  // it has no tense in any of its forms. That's the 1st/2nd personal pronouns
  // (ἐγώ, σύ), which genuinely lack a third person. Verbs always conjugate all
  // three persons, so we never flag a person on them: a verb paradigm that
  // happened to drill only some persons must not look like it "lacks" one it
  // actually has. This keeps the gap bulletproof against undrilled verb forms.
  const tensePool = presentValues.tense;
  if (tensePool && tensePool.size > 0) return null;
  if (pool.has(picked)) return null;                     // picked person exists here → fine
  const pickedGloss = PERSON_GLOSS[picked] || picked;
  const have = ['first', 'second', 'third'].filter((p) => pool.has(p)).map((p) => PERSON_GLOSS[p] || p);
  const haveList = have.length <= 1 ? `${have[0] || ''} person` : `${have.join(' and ')} person`;
  let note = `This paradigm has no ${pickedGloss}-person forms — only ${haveList}.`;
  if (picked === 'third') {
    note += ' The third-person personal pronoun is a separate paradigm (αὐτός, αὐτή, αὐτό).';
  }
  return {
    dim: 'person',
    picked,
    short: `no ${pickedGloss}-person form in this paradigm`,
    note
  };
}

// The picked value for some dim is in the paradigm's declared-lacking list AND
// isn't actually drilled (the guard trusts data over a stale curated entry).
// Currently only case=vocative for the article + pronouns.
function curatedGapReason(pickedDims, presentValues, curated) {
  for (const dim of Object.keys(curated)) {
    const pickedVal = pickedDims[dim];
    const lacking = curated[dim];
    if (!pickedVal || !Array.isArray(lacking) || !lacking.includes(pickedVal)) continue;
    const dimPool = presentValues[dim];
    if (dimPool && dimPool.has(pickedVal)) continue; // paradigm actually drills it → trust data
    if (dim === 'case' && pickedVal === 'vocative') {
      return {
        dim,
        picked: pickedVal,
        short: 'no vocative in this paradigm',
        note: 'Pronouns and the article have no vocative case — they inflect for the nominative, accusative, genitive, and dative only.'
      };
    }
    return {
      dim,
      picked: pickedVal,
      short: `no ${pickedVal} ${dim} in this paradigm`,
      note: `This paradigm has no ${pickedVal} ${dim}.`
    };
  }
  return null;
}

// Pedagogical hints appended to a lemma's inventory-gap note, keyed by lemma.
// Kept tiny and explicit — only verbs with a genuinely suppletive / defective
// paradigm worth a one-line explanation.
const LEMMA_GAP_HINTS = {
  'εἰμί': 'εἰμί is suppletive — its aorist and perfect senses come from other verbs (e.g. ἐγενόμην, γέγονα).'
};

// Gap descriptor from a lemma's reviewed negative inventory
// (impossibleTenses / impossibleVoices / impossibleMoods in
// js/data/lemma_inventory.js): a tense/voice/mood the lemma genuinely lacks in
// Greek — e.g. the non-existent aorist of εἰμί. Returns { dim, picked, short,
// note } or null. Reads ONLY the hand-curated inventory; it never infers a gap
// from forms that merely aren't drilled, so it can't misfire on an incomplete
// paradigm. Mirrors render.js's isParseImpossibleForLemma, but produces the
// early-cutoff reason rather than the end-of-walk "[no morph exists]" verdict.
export function lemmaInventoryGapReason(pickedDims, inv, lemma) {
  if (!pickedDims || !inv) return null;
  const lemmaName = lemma || 'this verb';
  const checks = [
    ['tense', inv.impossibleTenses],
    ['voice', inv.impossibleVoices],
    ['mood',  inv.impossibleMoods]
  ];
  for (const [dim, list] of checks) {
    const picked = pickedDims[dim];
    if (!picked || !Array.isArray(list) || !list.length) continue;
    // A picked value can be syncretic ('middle/passive'); any component
    // landing in the impossible list disqualifies the combination.
    const parts = String(picked).split('/').filter(Boolean);
    const bad = parts.find((p) => list.includes(p));
    if (!bad) continue;
    const norm = bad.replace(/^(first |second )/, ''); // "first aorist" → "aorist"
    let note = `${lemmaName} has no ${norm} forms in Koine.`;
    const hint = LEMMA_GAP_HINTS[lemma];
    if (hint) note += ` ${hint}`;
    return {
      dim,
      picked: bad,
      short: `no ${norm} ${dim} for ${lemmaName}`,
      note
    };
  }
  return null;
}

// ─── Accent / breathing look-alike distractors ──────────────────────────
//
// Curated minimal pairs: a drilled paradigm form and another Greek word that
// is spelled identically except for accent or breathing. In the reverse drill
// (English → Greek, pick the form) the look-alike is a clean "did you read the
// accent?" distractor — the focused paradigm tells the student WHICH word they
// want, and they must pick the correctly-accented spelling. Toggle-optional,
// off by default. Hand-authored: auto-generating wrong-accent forms risks
// emitting a real-but-mislabeled word.
//
// Keyed by the tested form (NFC). Each twin carries the wrong-spelling form
// plus a one-line note naming the distinction. Bidirectional where both sides
// are drilled paradigms (article ↔ relative; intensive αὐτός ↔ demonstrative
// οὗτος).
const ACCENT_LOOKALIKES_RAW = {
  // Article (proclitic, unaccented) ↔ relative pronoun (accented) — accent only
  'ὁ':  [{ form: 'ὅ',  note: 'ὅ (accented) is the relative pronoun (neut.); ὁ is the masculine article.' }],
  'ὅ':  [{ form: 'ὁ',  note: 'ὁ (unaccented) is the masculine article; ὅ is the relative pronoun (neut.).' }],
  'ἡ':  [{ form: 'ἥ',  note: 'ἥ (accented) is the relative pronoun (fem.); ἡ is the feminine article.' }],
  'ἥ':  [{ form: 'ἡ',  note: 'ἡ (unaccented) is the feminine article; ἥ is the relative pronoun (fem.).' }],
  'οἱ': [{ form: 'οἵ', note: 'οἵ (accented) is the relative pronoun (masc. pl.); οἱ is the masculine article.' }],
  'οἵ': [{ form: 'οἱ', note: 'οἱ (unaccented) is the masculine article; οἵ is the relative pronoun (masc. pl.).' }],
  'αἱ': [{ form: 'αἵ', note: 'αἵ (accented) is the relative pronoun (fem. pl.); αἱ is the feminine article.' }],
  'αἵ': [{ form: 'αἱ', note: 'αἱ (unaccented) is the feminine article; αἵ is the relative pronoun (fem. pl.).' }],
  // Intensive αὐτός ↔ near demonstrative οὗτος — breathing (+ accent placement)
  'αὐτή': [{ form: 'αὕτη', note: 'αὕτη (rough breathing) is the demonstrative “this”; αὐτή (smooth) is αὐτός “she / herself”.' }],
  'αὕτη': [{ form: 'αὐτή', note: 'αὐτή (smooth breathing) is αὐτός “she / herself”; αὕτη (rough) is the demonstrative “this”.' }],
  // Interrogative (accented) ↔ indefinite (enclitic, unaccented) — accent only
  'τίς': [{ form: 'τις', note: 'τις (unaccented enclitic) is the indefinite “someone”; τίς (accented) is the interrogative “who?”.' }],
  'τί':  [{ form: 'τι',  note: 'τι (unaccented enclitic) is the indefinite “something”; τί (accented) is the interrogative “what? / why?”.' }],
  // εἰμί 2 sg. ↔ conjunction — accent only
  'εἶ':  [{ form: 'εἰ',  note: 'εἰ is the conjunction “if”; εἶ (circumflex) is εἰμί “you are”.' }]
};

// NFC-normalized index, built once, so lookups match regardless of the
// composed/decomposed form of the incoming card's Greek string.
const ACCENT_LOOKALIKES = (() => {
  const out = {};
  for (const [key, twins] of Object.entries(ACCENT_LOOKALIKES_RAW)) {
    out[key.normalize('NFC')] = twins.map((t) => ({ form: String(t.form).normalize('NFC'), note: t.note }));
  }
  return out;
})();

// Returns the curated accent/breathing look-alikes for a tested form
// ([{ form, note }, …]), or [] when none. NFC-normalizes the query.
export function accentLookalikesFor(form) {
  if (!form) return [];
  const key = String(form).trim().normalize('NFC');
  return ACCENT_LOOKALIKES[key] || [];
}

// Builds an ungraded follow-up step for the given dimension. Choices come
// from the chapter-gated accessible pool when available; falls back to
// the full DIM_POOLS. The returned step has `inferred: true` and no
// `correct` value — it's scored as informational, not graded against the
// source card.
export function buildInferredStep(dimKey, accessiblePools, options = {}) {
  let pool = (accessiblePools && Array.isArray(accessiblePools[dimKey]) && accessiblePools[dimKey].length)
    ? accessiblePools[dimKey]
    : (DIM_POOLS[dimKey] || []);
  // An imperative's person is only ever 2nd or 3rd (no 1st in Koine), so an
  // inferred person step added by an imperative pick offers just those two.
  if (dimKey === 'person' && options.mood === 'imperative') {
    pool = ['second', 'third'];
  }
  if (!pool.length) return null;
  const choices = sortChoicesCanonically(dimKey, pool);
  const displayChoices = choices.map((c) => applyDisplaySuffix(dimKey, c));
  return {
    key: dimKey,
    label: DIM_LABEL[dimKey] || dimKey,
    correct: null,
    acceptable: [],
    choices,
    displayCorrect: '',
    displayChoices,
    inferred: true
  };
}

// Chapter at which Duff makes voice a parsing decision. Before the gate
// the voice step is suppressed (regardless of the card's own voice) and
// the value is silently filled in for the form lookup, since the only
// thing the step could ask is "pick active" or "name the voice of a
// deponent" — neither of which Duff treats as a parse the student
// commits to yet.
//
// The gate is form-type aware, because Duff introduces the voice
// contrast for participles a chapter before the finite system:
//   • Participles (Ch 14, "Participles") are taught across all voices at
//     once — present active λύων vs. present mid/pass λυόμενος vs. aorist
//     passive λυθείς — so distinguishing the voice IS the parse from Ch 14.
//   • Finite verbs (Ch 15, "The Passive and Voices") only get the full
//     active/middle/passive system — and the rule that a deponent's
//     middle/passive form counts as functionally active — at Ch 15.
// Gating both to 15 would hide voice exactly when a Ch-14 student starts
// drilling middle/passive participles; gating both to 14 would wrongly
// start asking "what voice is ἔρχεται?" for finite deponents a chapter
// early. So participle cards use the earlier gate, everything else the
// later one.
const VOICE_INTRODUCED_AT_CHAPTER = 15;
const VOICE_INTRODUCED_AT_CHAPTER_PARTICIPLE = 14;

// Duff introduces the 3rd-person imperative (λυέτω "let him/her/it loose",
// λυέτωσαN "let them loose") in ch 18 ("Using Verbs") — ch 17 is the
// subjunctive. The matching paradigm set (W7_THIRD_PERSON_IMPERATIVE) is gated
// to ch 18, so this constant must agree: before ch 18 every imperative in
// scope is 2nd person and the parsing walk treats an imperative's person as
// structurally fixed (step skipped, 2nd person implied); from ch 18 the 2nd/3rd
// contrast is real, so the person step is asked. There is no 1st-person
// imperative in Koine, so the step (when shown) only ever offers 2nd / 3rd.
export const THIRD_PERSON_IMPERATIVE_CHAPTER = 18;

// A deponent verb's dictionary form is itself middle/passive (ends in -μαι):
// γίνομαι, ἔρχομαι, δέχομαι, δύναμαι… These are middle/passive in form but
// active in meaning, so Duff parses their voice as active. A regular verb
// (λύω, λαμβάνω…) keeps a genuine middle voice — its middle forms (ἐλύσω "you
// loosed for yourself") are NOT active and must grade strictly. εἰμί is the one
// active-lemma exception whose future (ἔσομαι) is deponent in form.
function isDeponentLemma(lemma) {
  if (!lemma) return false;
  const l = String(lemma).trim();
  return /μαι$/.test(l) || l === 'εἰμί';
}

// Tenses where the middle and passive share a single form. In the present,
// imperfect, perfect, and pluperfect a form like λύομαι is equally middle
// ("I loose for myself") and passive ("I am loosed") — there's no spelling
// that picks one; only context does. The future and aorist DO spell them
// apart (future middle λύσομαι vs passive λυθήσομαι; aorist middle ἐλυσάμην
// vs passive ἐλύθην), so they're excluded. Used to widen the voice step's
// accepted answers for these tenses (see buildMorphSteps).
const MIDDLE_PASSIVE_SYNCRETIC_TENSES = new Set(['present', 'imperfect', 'perfect', 'pluperfect']);

// True when a card's voice is the syncretic middle/passive of a present /
// imperfect / perfect / pluperfect non-deponent verb — the tenses where one
// form (λύομαι) serves both voices, so a one-sidedly-labelled 'passive' (or
// 'middle') card should be read as the combined 'middle/passive' and accept
// either reading. The future/aorist (which spell the voices apart) and
// deponents (covered by the active-accepting rule) are excluded. Shared by the
// parsing drill (buildMorphSteps) and the Lookup-mode pool (buildLookupPool) so
// the two surfaces expose exactly the same set of legitimate voices.
export function isSyncreticMiddlePassiveVoice(dims, lemma) {
  if (!dims) return false;
  const voice = dims.voice;
  return MIDDLE_PASSIVE_SYNCRETIC_TENSES.has(dims.tense)
    && (voice === 'middle' || voice === 'passive' || voice === 'middle/passive')
    && !isDeponentLemma(lemma);
}

// Returns ordered dimension steps for this card. Each step:
//   { key, label, correct, choices, displayChoices, displayCorrect }
// `accessiblePools` is the optional chapter-gated distractor pool produced by
// computeAccessibleDimensionPools — pass it in to restrict MC choices to
// values the textbook has introduced so far.
// `options.includeAspect` (default true) controls whether the walk asks the
// Aspect step. Aspect is derivable from tense, so users who don't want to
// drill the composite-vs-single distinction (continuous/undefined vs
// continuous) can turn it off.
// `options.maxChapter` is the student's max effective chapter (from
// deriveSelectionLevels). Used to gate the voice step.
export function buildMorphSteps(card, accessiblePools = null, options = {}) {
  if (!card || card.kind !== 'morph') return [];
  // Prefer the canonical parsed form when set — grammar.js cards can ship
  // a sparse human-friendly `answer` ("1st singular ('I am')") alongside
  // a `parsed:` ("present active indicative first person singular") that
  // populates every dimension the form actually carries.
  const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
  // First/second aorist is a stem-formation distinction (first/weak vs
  // second/strong), not a separate tense — both parse as the aorist. Collapse
  // the qualifier so the Tense step asks for, accepts, and reports plain
  // "aorist" for every aorist form rather than treating "first aorist" /
  // "second aorist" as distinct tense answers. Aspect stays correct (aspectFor
  // Tense maps all three to 'undefined') and the stem-change summary footer
  // re-derives the qualifier from card.answer, so neither is affected.
  if (dims.tense) dims.tense = dims.tense.replace(/^(first |second )/, '');
  const includeAspect = options.includeAspect !== false;

  // Chapter-gated mood default. When the card is a finite verb (tense +
  // person/number, no case/gender) with no explicit mood in its parse,
  // AND the student's accessible pool already contains a non-indicative
  // mood (i.e. the curriculum has introduced something else to contrast
  // against), inject mood='indicative' so the Mood step appears and the
  // student commits explicitly rather than having indicative silently
  // implied. Before the contrast exists (early chapters), the Mood step
  // would be a no-info "pick indicative" — skipped.
  if (!dims.mood && (dims.tense || dims.voice) && (dims.person || dims.number)
      && !dims.case && !dims.gender) {
    const accessibleMoods = (accessiblePools && Array.isArray(accessiblePools.mood)) ? accessiblePools.mood : [];
    const hasContrast = accessibleMoods.some(m => m && m !== 'indicative');
    if (hasContrast) dims.mood = 'indicative';
  }

  // Determine the dimension order. Verbs lead with aspect → tense (Duff's
  // aspect-first pedagogy), then voice → mood → person → number, with a
  // case/number/gender tail for participles. Nominals skip the verb steps.
  const isVerb = !!(dims.tense || dims.voice || dims.person);
  const verbOrder = ['aspect', 'tense', 'voice', 'mood', 'person', 'case', 'number', 'gender'];
  const nominalOrder = ['case', 'number', 'gender', 'aspect', 'tense', 'voice', 'mood', 'person'];
  const order = (isVerb ? verbOrder : nominalOrder).filter(k => includeAspect || k !== 'aspect');

  const steps = [];
  const skippedCorrect = {}; // dim → correct value for steps we silently skipped
  const impliedDims = {};    // dim → correct value for steps skipped but kept in parse summary
  const maxChapter = Number.isFinite(options.maxChapter) ? options.maxChapter : Infinity;
  const dimToggles = (options.dimToggles && typeof options.dimToggles === 'object') ? options.dimToggles : null;
  const dimValueFilters = (options.dimValueFilters && typeof options.dimValueFilters === 'object') ? options.dimValueFilters : null;
  const multiGenderLemmas = options.multiGenderLemmas instanceof Set ? options.multiGenderLemmas : null;
  // Single-gender lemmas whose gender is non-obvious from the form
  // ending (1st-decl. masc. -ης/-ας nouns: προφήτης, μαθητής, …) —
  // override the single-gender auto-skip below so the gender step IS
  // asked. The form looks feminine; recalling the lemma is masculine is
  // the whole point of the drill for these.
  const mixedFormNouns = options.mixedFormNouns instanceof Set ? options.mixedFormNouns : null;
  // Third-declension nouns (σάρξ, ὄνομα, βασιλεύς, …) get the same treatment:
  // single-gender, but the gender doesn't follow from the ending, so the
  // gender step stays IN rather than being auto-skipped. See
  // THIRD_DECLENSION_NOUN_LEMMAS in paradigm_focus.js.
  const thirdDeclensionNouns = options.thirdDeclensionNouns instanceof Set ? options.thirdDeclensionNouns : null;
  for (const dimKey of order) {
    const correct = dims[dimKey];
    if (!correct) continue;
    // Imperatives have no 1st person, and Duff teaches only the 2nd until
    // ch 17 (which adds the 3rd: λυέτω). Below that gate an imperative's
    // person is structurally 2nd, so skip the step — but record it
    // (skippedCorrect + impliedDims) so the form lookup and the parse summary
    // still carry the person rather than silently dropping it (a 3rd-person
    // imperative would otherwise mis-read as 2nd). From ch 17 the step stays,
    // so the student commits to 2nd vs 3rd; its choices are restricted to
    // 2nd/3rd below.
    if (dimKey === 'person' && dims.mood === 'imperative'
        && maxChapter < THIRD_PERSON_IMPERATIVE_CHAPTER) {
      skippedCorrect[dimKey] = correct;
      impliedDims[dimKey] = correct;
      continue;
    }
    // Voice step: gate on chapter, with an earlier gate for participles.
    // Duff doesn't ask the student to choose a voice for finite verbs
    // until ch 15 — the deponent forms covered at ch 8/9 are taught as
    // functionally active (middle/passive in form, active in meaning),
    // so asking "what voice is ἔρχεται?" at ch 9 is a question Duff
    // doesn't expect a single right answer to. Participles, though, are
    // introduced at ch 14 across active / middle / passive at once
    // (λύων / λυόμενος / λυθείς), so naming a participle's voice is the
    // parse from ch 14. Below the relevant gate the voice gets silently
    // filled in (skippedCorrect) so the form lookup still resolves; at
    // or after it the step appears, with the deponent-accepts-active
    // rule applied when the step is built below.
    if (dimKey === 'voice') {
      const voiceGateChapter = dims.mood === 'participle'
        ? VOICE_INTRODUCED_AT_CHAPTER_PARTICIPLE
        : VOICE_INTRODUCED_AT_CHAPTER;
      if (maxChapter < voiceGateChapter) {
        skippedCorrect[dimKey] = correct;
        continue;
      }
    }
    // Per-dim toggle: user-controlled opt-out. Off → step skipped, dim
    // doesn't contribute to stats, omitted from the parse summary; the
    // form lookup auto-fills the canonical correct value via
    // skippedCorrect below.
    if (dimToggles && dimKey !== 'aspect' && dimToggles[dimKey] === false) {
      skippedCorrect[dimKey] = correct;
      continue;
    }
    // Single-gender noun gender step. A noun like λόγος (masc.), ἀγάπη (fem.),
    // or ἔργον (neut.) has one fixed gender across its whole paradigm — the form
    // λόγου is masculine because λόγος is, not because the genitive ending picks
    // a gender. Drilling it as a real multi-choice test would probe lemma memory,
    // not form-parsing; auto-skipping it (the old behavior) hid the gender from
    // the walk entirely. Instead show a single-option reinforcement step — one
    // button for the noun's gender, with a note naming the noun type — so the
    // gender↔noun-type link is reinforced without being a guessable test. Marked
    // `fixedGenderNoun` here and turned into a single-choice step below.
    //
    // Multi-gender paradigms (articles, adjectives, pronouns, participles) are
    // excluded — there the form genuinely commits to a gender, so they keep the
    // normal multi-choice step. So are mixed-form -ης/-ας masculines (προφήτης,
    // μαθητής, whose endings mimic the 1st-decl. feminine) and 3rd-declension
    // nouns (σάρξ fem., ὄνομα neut., βασιλεύς masc.): their gender has to be
    // recalled (σαρκός gives no tell), so they stay a real multi-choice test.
    const isMixedFormNoun = !!(mixedFormNouns && card.lemma && mixedFormNouns.has(card.lemma));
    const isThirdDeclNoun = !!(thirdDeclensionNouns && card.lemma && thirdDeclensionNouns.has(card.lemma));
    const fixedGenderNoun = dimKey === 'gender' && !!multiGenderLemmas && !!card.lemma
      && !multiGenderLemmas.has(card.lemma)
      && !isMixedFormNoun && !isThirdDeclNoun;
    let pool = accessiblePools ? accessiblePools[dimKey] : null;
    // No 1st-person imperative exists in Koine — when the person step is asked
    // for an imperative (ch 17+), offer only 2nd / 3rd as choices.
    if (dimKey === 'person' && dims.mood === 'imperative') {
      pool = ['second', 'third'];
    }
    // Syncretic middle/passive collapse. A non-deponent verb's present /
    // imperfect / perfect / pluperfect middle and passive are the same form
    // (λύομαι), so a card the source set labelled one-sidedly ("λύω — passive
    // indicative") should parse as the combined 'middle/passive' and accept
    // either reading. The future/aorist (where the two voices diverge) and
    // deponents (handled by the middle-only rule below) are left untouched.
    // Collapsing before buildChoices makes 'middle/passive' a real option and
    // the headline correct value, so the correction never points at a voice the
    // student couldn't have picked.
    const syncreticMiddlePassive = dimKey === 'voice'
      && isSyncreticMiddlePassiveVoice(dims, card.lemma);
    // Deponent voice = middle. A deponent's dictionary form is medio-passive in
    // shape, but the verb has no active form to contrast and (being deponent) no
    // passive sense — so its voice is simply the middle. Instead of asking
    // active-vs-middle (the old "deponent counts as active" soft-accept), the
    // step offers a single 'middle' choice plus a note: modern scholarship reads
    // deponents as genuine middles, while the traditional framing calls them
    // "middle in form, active in meaning". Guarded to the middle / middle-passive
    // voices so a deponent's genuinely passive forms (γίνομαι's aorist passive
    // ἐγενήθην, the θη-aorists of passive deponents like ἀπεκρίθην) stay a strict
    // 'passive', and to deponent lemmas so a regular verb's middle/passive
    // (λύομαι) keeps the syncretic treatment above — λύω is not deponent and not
    // middle-only.
    const deponentMiddleOnly = dimKey === 'voice'
      && (correct === 'middle' || correct === 'middle/passive')
      && isDeponentLemma(card.lemma);
    const stepCorrect = deponentMiddleOnly
      ? 'middle'
      : (syncreticMiddlePassive ? 'middle/passive' : correct);
    // Single-option steps show one button and skip the distractor pool: the
    // deponent voice step ('middle' only) and the single-gender noun's gender
    // step (its one fixed gender). Every other dimension draws its distractors
    // from the chapter-gated accessible pool.
    let choices;
    if (deponentMiddleOnly) choices = ['middle'];
    else if (fixedGenderNoun) choices = [stepCorrect];
    else choices = buildChoices(dimKey, stepCorrect, pool, dimValueFilters);
    const displayCorrect = applyDisplaySuffix(dimKey, stepCorrect);
    const displayChoices = choices.map((c) => applyDisplaySuffix(dimKey, c));
    // Each dimension has exactly one correct value per card. For aspect on
    // present/future verbs the correct value is the composite
    // 'continuous/undefined' (since either reading is licensed by the form);
    // for imperfect/aorist/perfect/pluperfect it's a single specific aspect.
    // The aspect step carries a `context.tense` so the wrong-answer
    // comparator can spell out the mistake when picked and correct overlap
    // visually (e.g. picked "continuous" vs correct "continuous/undefined").
    const step = {
      key: dimKey,
      label: DIM_LABEL[dimKey] || dimKey,
      correct: stepCorrect,
      acceptable: [stepCorrect],
      choices,
      displayCorrect,
      displayChoices
    };
    if (dimKey === 'aspect' && dims.tense) {
      step.context = { tense: dims.tense };
    }
    // For the syncretic m/p tenses, accept the bare 'middle' and 'passive'
    // picks too (not just the combined option) — either reading is right.
    if (syncreticMiddlePassive) {
      step.acceptable = ['middle/passive', 'middle', 'passive'];
    }
    // Flag the deponent middle-only voice step so the renderer shows the single
    // centered 'Middle' choice with its contested-voice note. `acceptable` is
    // already ['middle'] (from stepCorrect), so grading stays strict — there's
    // no 'active' option to pick, replacing the old "deponent counts as active"
    // soft-accept. The chapter gate still applies (ch 14+ participles, ch 15+
    // finite); below it the voice is silently filled and never asked.
    if (deponentMiddleOnly) {
      step.deponentMiddleOnly = true;
    }
    // Flag the single-gender noun's gender step so the renderer shows the lone
    // centered button with a noun-type note. `acceptable` is already the one
    // gender (from stepCorrect), so it can't be answered wrong — it's
    // reinforcement, not a test.
    if (fixedGenderNoun) {
      step.fixedGender = true;
    }
    if (dimKey === 'mood' && isSecondPluralPresentMoodAmbiguity(card.answer, dims)) {
      step.acceptable = ['indicative', 'imperative'];
    }
    steps.push(step);
  }
  // Attach the auto-filled-correct dim map as a property on the array
  // (rather than changing the return shape) so the caller can read it
  // alongside the steps for the form-lookup augmentation, while
  // callers that just want the step list keep working.
  steps.autoFilledDims = skippedCorrect;
  // `impliedDims` is a subset of skippedCorrect (currently just the
  // single-gender gender skip) that should still appear in the rendered
  // parse summary — the step wasn't asked, but the dim belongs to the
  // form's canonical label. Caller renders these inline with the
  // student-picked values.
  steps.impliedDims = impliedDims;
  return steps;
}

// ─── Per-lemma drill stats ──────────────────────────────────────────────
//
// Two structures per lemma:
//   - `attempts`:  sliding window of the last ATTEMPT_WINDOW raw attempts.
//                  Drives the header pct + the in-card "Last 20 attempts"
//                  rollup. Per-attempt, per-dimension correctness.
//   - `forms`:     { [cardId]: { seen, recent: [up to FORM_HISTORY_CAP
//                  per-dim results] } }. The canonical per-form record: dots
//                  the testable-forms list, feeds the exclude-known-morphs
//                  filter, and — joined with each form's parsed dimension
//                  *values* — drives the per-value (per-mood / per-tense)
//                  proficiency breakdown.
//
//                  The stored history is deliberately deeper than the
//                  exclude-known threshold so the confidence breakdown has
//                  more than two attempts to average per form (the headline
//                  and per-value bars are otherwise jittery, especially in
//                  the all-paradigms shuffle where each form is seen rarely).
//                  Two read windows over the one array keep the concerns
//                  separate: the exclude-known "2/2 known" filter and the
//                  testable-forms dots only ever look at the last
//                  FORM_RECENT_CAP attempts (so that behaviour is unchanged),
//                  while the confidence views read the full FORM_HISTORY_CAP.
//
// No cross-paradigm `overall` mirror and no disjoint bucket history are
// persisted: the breakdown is derived from `forms` at read time, so the
// aggregate views cost nothing extra in the save beyond the deeper per-form
// history itself.

const ATTEMPT_WINDOW = 20;

export function ensureParadigmStepStats(store) {
  if (!store || typeof store !== 'object') return {};
  if (typeof store.byLemma !== 'object' || store.byLemma === null) store.byLemma = {};
  return store;
}

function ensureLemmaEntry(entry) {
  if (!Array.isArray(entry.attempts)) entry.attempts = [];
  if (!entry.forms || typeof entry.forms !== 'object') entry.forms = {};
  return entry;
}

// Last-N window that defines "known" for the exclude-known-morphs filter and
// the testable-forms dots. NOT the storage depth — see FORM_HISTORY_CAP. This
// stays 2 so the 2/2 "known" rule is untouched.
export const FORM_RECENT_CAP = 2;

// Per-dimension credit for a PARTIAL composite answer: naming one valid value
// of a multi-value (syncretic) form — e.g. picking 'nominative' for a
// 'nominative/accusative' neuter, or 'masculine' for a 'masculine/neuter'
// form. It's accepted (the form advances and the shuffler treats it as correct)
// but, being < 1, never satisfies the strict 2/2 "known" test (evaluateRecent
// Attempt requires an exact 1), so the form is never excluded as mastered until
// the student names the FULL composite. Worth 0.75 in the accuracy stats. Must
// survive a save round-trip — see sanitizeDimCredit in persistence.js, which
// snaps to this same value.
export const PARTIAL_COMPOSITE_CREDIT = 0.75;

// True when `picked` names a proper, non-empty SUBSET of a multi-value
// (slash-composite) correct answer — e.g. 'nominative' for 'nominative/
// accusative', 'masculine' for 'masculine/neuter', or 'continuous' for the
// present/future aspect 'continuous/undefined'. Scoped to case, gender, and
// aspect — the syncretisms the drill rewards partially. Voice's middle/passive
// is already accepted in full via step.acceptable, so it's excluded (it stays
// full credit, not partial). Returns false for the full composite or an exact
// pick (plain-correct) and for any value carrying a component outside the
// correct set (plain-wrong).
export function isPartialCompositePick(step, picked) {
  if (!step || !picked) return false;
  if (step.key !== 'case' && step.key !== 'gender' && step.key !== 'aspect') return false;
  const correct = String(step.correct || '');
  if (!correct.includes('/')) return false;            // not a composite answer
  const acceptable = Array.isArray(step.acceptable) && step.acceptable.length
    ? step.acceptable : [correct];
  if (acceptable.includes(picked)) return false;       // already fully accepted
  if (picked === correct) return false;                // full composite = full credit
  const correctParts = new Set(correct.split('/').filter(Boolean));
  const pickedParts = String(picked).split('/').filter(Boolean);
  if (!pickedParts.length || pickedParts.length >= correctParts.size) return false;
  return pickedParts.every((p) => correctParts.has(p));
}
// How many recent per-form attempts to STORE. Deeper than FORM_RECENT_CAP so
// the confidence views (headline % + per-value bars) have more than two
// attempts to average per form; the exclude-known filter and dots still only
// read the last FORM_RECENT_CAP of these. Bump with care — it's persisted
// per drilled form (see sanitizeFormRecentList in persistence.js, which caps
// to the same depth).
const FORM_HISTORY_CAP = 10;

// Record one attempt: a fully walked card with per-dimension credit. Each dim
// value is 1 (clean correct), a fraction (reattempted via undo, re-picked
// correctly — 0.25 for a single undo, halving again for each extra undo: 0.125,
// 0.0625, …), or 0 (wrong). The accuracy aggregators sum the value (so a
// reattempt counts fractionally), while evaluateRecentAttempt's "known" test
// requires an exact 1, so any reattempt keeps the form out of the 2/2
// exclude-known set.
// stats: { byLemma: { lemma: { attempts: [{at, dims}],
//                              forms: { [cardId]: { seen, recent: [{dims}] } } } } }
// `formMeta` is optional: { cardId } stores the most recent FORM_HISTORY_CAP
// per-dim results so the testable-forms list can dot each form by its last
// 1–2 attempts, the exclude-known-morphs filter can skip mastered forms, and
// the per-value breakdown can roll each form into its mood/tense/voice value.
export function recordParadigmAttempt(stats, lemma, dimResults, formMeta) {
  if (!lemma || !dimResults) return;
  ensureParadigmStepStats(stats);
  if (!stats.byLemma[lemma]) stats.byLemma[lemma] = {};
  const entry = ensureLemmaEntry(stats.byLemma[lemma]);

  if (formMeta && formMeta.cardId) {
    const prior = entry.forms[formMeta.cardId];
    const prevSeen = prior && Number.isFinite(prior.seen) ? prior.seen : 0;
    const priorRecent = Array.isArray(prior && prior.recent) ? prior.recent : [];
    const recent = priorRecent.concat([{ dims: { ...dimResults } }]).slice(-FORM_HISTORY_CAP);
    entry.forms[formMeta.cardId] = { seen: prevSeen + 1, recent };
  }

  // Sliding window of raw attempts (drives the header pct + the in-card
  // "Last 20 attempts" rollup). Per-attempt, per-dimension correctness.
  entry.attempts.push({ at: Date.now(), dims: { ...dimResults } });
  while (entry.attempts.length > ATTEMPT_WINDOW) entry.attempts.shift();
}

// True if the given dim is currently enabled. `enabledDims` is the map
// returned by getEnabledParsingDims (main.js); a null/undefined value is
// treated as "all dims enabled" so callers that don't care about filters
// (e.g. import sanitization) still get the historical totals.
function isDimEnabled(enabledDims, dim) {
  if (!enabledDims) return true;
  return enabledDims[dim] !== false;
}

// Half-credit for an incomplete parse in the headline accuracy %. A parse
// where the student missed at least one (enabled) dimension contributes its
// correct dimensions at this weight, so completing a parse counts for more
// than a partially-right one. Only the weighted accuracy (`weightedCorrect`)
// uses this — the raw `correct`/`total` per-dimension counts are untouched,
// so the per-card "X/Y dimensions correct" readout stays literal.
const WRONG_PARSE_CREDIT = 0.5;

// Aggregate accuracy for a single lemma's recent attempts. When
// `enabledDims` is provided, per-dim values whose dim is currently
// toggled off are skipped — they don't contribute to the totals or to
// the per-dim chips, matching the user's current parsing scope.
//
// Returns raw `correct`/`total` (per-dimension hit counts) plus
// `weightedCorrect`, which discounts the correct dimensions of any
// not-fully-correct parse by WRONG_PARSE_CREDIT. Callers showing the
// headline accuracy % divide weightedCorrect / total; callers reporting a
// literal dimension tally use correct / total.
export function summarizeLemmaStats(stats, lemma, enabledDims) {
  const empty = { total: 0, correct: 0, weightedCorrect: 0, perDim: {}, attempts: 0 };
  if (!stats || !stats.byLemma || !stats.byLemma[lemma]) return empty;
  const attempts = stats.byLemma[lemma].attempts || [];
  let total = 0, correct = 0, weightedCorrect = 0;
  const perDim = {};
  for (const a of attempts) {
    if (!a || !a.dims) continue;
    let attemptTotal = 0, attemptCorrect = 0;
    for (const [dim, val] of Object.entries(a.dims)) {
      if (!isDimEnabled(enabledDims, dim)) continue;
      // `val` is fractional credit: 1 = clean correct, a fraction (0.25, 0.125,
      // …, halving per undo) = reattempted via undo (re-picked right), 0 =
      // wrong. Sum it so a reattempt counts fractionally.
      const credit = Number(val) || 0;
      if (!perDim[dim]) perDim[dim] = { seen: 0, correct: 0 };
      perDim[dim].seen += 1;
      perDim[dim].correct += credit;
      attemptTotal += 1;
      attemptCorrect += credit;
    }
    if (!attemptTotal) continue;
    total += attemptTotal;
    correct += attemptCorrect;
    weightedCorrect += attemptCorrect === attemptTotal
      ? attemptCorrect
      : attemptCorrect * WRONG_PARSE_CREDIT;
  }
  return { total, correct, weightedCorrect, perDim, attempts: attempts.length };
}

export function getAllLemmaStats(stats, enabledDims) {
  if (!stats || !stats.byLemma) return [];
  return Object.keys(stats.byLemma).map((lemma) => ({
    lemma,
    ...summarizeLemmaStats(stats, lemma, enabledDims)
  })).filter((s) => s.attempts > 0);
}

export function getParadigmStepDimensionLabel(dimKey) {
  return DIM_LABEL[dimKey] || dimKey;
}

// Default parses-per-bucket for the accuracy-over-guesses trend (analytics).
export const PARSING_ACCURACY_BUCKET_SIZE = 20;

// Roll every recorded parse (across all paradigms) into chronological buckets
// so the analytics overlay can chart accuracy *over guesses* — i.e. whether
// recent parses are getting more accurate, not just the per-paradigm averages.
//
// Each lemma keeps only its last ATTEMPT_WINDOW (20) attempts, so this is a
// recent-history view by construction, not the full lifetime log. Attempts are
// pooled across lemmas, sorted by time, and sliced into `bucketSize`-wide
// groups. Buckets are aligned from the *most recent* end so the rightmost
// (latest) bar is always a full bucket and any short bucket is the oldest one
// on the left — the freshest, most-watched number is never a 1-parse fluke.
//
// `enabledDims` scopes accuracy to the parse steps the user currently has on,
// matching every other number in the parsing analytics section. Two metrics
// per bucket: `fullPct` (share of parses with every enabled dim correct — the
// headline "got the whole parse right") and `dimPct` (share of individual
// dimensions correct — the gentler partial-credit view).
export function getParsingAccuracyBuckets(stats, enabledDims, bucketSize = PARSING_ACCURACY_BUCKET_SIZE) {
  if (!stats || !stats.byLemma) return { buckets: [], totalParses: 0 };
  const all = [];
  for (const lemma of Object.keys(stats.byLemma)) {
    const attempts = (stats.byLemma[lemma] && stats.byLemma[lemma].attempts) || [];
    for (const a of attempts) {
      if (!a || !a.dims) continue;
      let total = 0, correct = 0, sawMiss = false, sawHalf = false;
      for (const [dim, val] of Object.entries(a.dims)) {
        if (!isDimEnabled(enabledDims, dim)) continue;
        total += 1;
        // Fractional credit: a fraction (0.25, 0.125, … per undo) for a
        // reattempted dim, 1 for a clean correct one. A parse is `full` only
        // when every dim is exactly 1, so a reattempt (correct < total) is
        // never counted as fully correct.
        correct += Number(val) || 0;
        if (val === 0) sawMiss = true;
        else if (val !== 1) sawHalf = true;
      }
      if (!total) continue;
      // 3-tier whole-parse outcome for the outcome-mix chart.
      const outcome = sawMiss ? 'missed' : sawHalf ? 'reattempted' : 'clean';
      all.push({ at: Number(a.at) || 0, total, correct, full: correct === total, outcome });
    }
  }
  all.sort((x, y) => x.at - y.at);
  const n = all.length;
  if (!n) return { buckets: [], totalParses: 0 };
  const size = Math.max(1, Math.floor(bucketSize) || PARSING_ACCURACY_BUCKET_SIZE);

  // Bucket boundaries aligned from the end (see header): a short leading bucket
  // absorbs the remainder so every later bucket is full.
  const boundaries = [];
  const rem = n % size;
  let idx = 0;
  if (rem > 0) { boundaries.push([0, rem]); idx = rem; }
  for (; idx < n; idx += size) boundaries.push([idx, idx + size]);

  const overall = { clean: 0, reattempted: 0, missed: 0 };
  const buckets = boundaries.map(([start, end], i) => {
    const slice = all.slice(start, end);
    let dims = 0, dimsCorrect = 0, fulls = 0;
    let clean = 0, reattempted = 0, missed = 0;
    for (const s of slice) {
      dims += s.total;
      dimsCorrect += s.correct;
      if (s.full) fulls += 1;
      if (s.outcome === 'clean') clean += 1;
      else if (s.outcome === 'reattempted') reattempted += 1;
      else missed += 1;
    }
    overall.clean += clean;
    overall.reattempted += reattempted;
    overall.missed += missed;
    const count = slice.length;
    return {
      index: i,
      count,
      first: start + 1,
      last: Math.min(end, n),
      fulls,
      fullPct: count ? Math.round((fulls / count) * 100) : 0,
      dimPct: dims ? Math.round((dimsCorrect / dims) * 100) : 0,
      // 3-tier outcome counts for the outcome-mix chart.
      clean,
      reattempted,
      missed
    };
  });
  return { buckets, totalParses: n, outcomes: overall };
}

// Re-evaluate a single recent attempt under the user's current dim toggles.
// Legacy attempts (saved before per-dim recording, only `allDims: bool`) keep
// their stored verdict since we no longer have the per-dim breakdown.
//
// Binary "clean parse" test: true only when every enabled dim is exactly 1.
// This is the strict rule the exclude-known deck filter and the form dots use —
// a reattempt (0.5) keeps a form out of "known" — so it stays whole-parse-binary
// on purpose. The half-credit, per-dimension accuracy view used by the headline
// % and per-value bars lives in countLemmaFormDimCredit below.
function evaluateRecentAttempt(attempt, enabledDims) {
  if (!attempt) return false;
  if (typeof attempt.allDims === 'boolean') return attempt.allDims;
  const dims = attempt.dims || {};
  for (const [dim, val] of Object.entries(dims)) {
    if (!isDimEnabled(enabledDims, dim)) continue;
    if (val !== 1) return false;
  }
  return true;
}

// Tally for one form, after filtering disabled dims. Returns
// { correct, total } where total is the number of recorded recent attempts
// considered and correct is how many of those pass every currently-enabled
// dim. `windowSize` limits the count to the last N stored attempts: the
// exclude-known / dot callers pass FORM_RECENT_CAP (the unchanged 2/2 rule),
// while the confidence breakdown omits it to use the full FORM_HISTORY_CAP
// history for a steadier estimate.
export function countLemmaFormRecent(stats, lemma, cardId, enabledDims, windowSize) {
  if (!cardId) return { correct: 0, total: 0 };
  const entry = stats?.byLemma?.[lemma];
  const form = entry?.forms && entry.forms[cardId];
  if (!form || !Array.isArray(form.recent) || !form.recent.length) {
    return { correct: 0, total: 0 };
  }
  const list = (Number.isInteger(windowSize) && windowSize > 0)
    ? form.recent.slice(-windowSize)
    : form.recent;
  let correct = 0;
  for (const a of list) {
    if (evaluateRecentAttempt(a, enabledDims)) correct += 1;
  }
  return { correct, total: list.length };
}

// Per-DIMENSION half-credit accuracy for one form: sums each enabled
// dimension's own credit (1 clean / 0.5 reattempted / 0 missed) across the
// form's recent attempts, with `total` the number of dimension-slots counted.
// So a parse that got 4 of 5 dimensions right contributes 4/5 here — not the 0
// the whole-parse countLemmaFormRecent gives it. This is what the headline %
// and the per-value bars report (a dimension-level proficiency), while the
// dots / exclude-known filter keep the strict whole-parse 2/2 rule. Legacy
// `allDims` attempts (no per-dim record) collapse to a single 1/0 slot.
export function countLemmaFormDimCredit(stats, lemma, cardId, enabledDims, windowSize) {
  if (!cardId) return { correct: 0, total: 0 };
  const entry = stats?.byLemma?.[lemma];
  const form = entry?.forms && entry.forms[cardId];
  if (!form || !Array.isArray(form.recent) || !form.recent.length) {
    return { correct: 0, total: 0 };
  }
  const list = (Number.isInteger(windowSize) && windowSize > 0)
    ? form.recent.slice(-windowSize)
    : form.recent;
  let correct = 0;
  let total = 0;
  for (const a of list) {
    if (typeof a.allDims === 'boolean') { correct += a.allDims ? 1 : 0; total += 1; continue; }
    const dims = a.dims || {};
    for (const [dim, val] of Object.entries(dims)) {
      if (!isDimEnabled(enabledDims, dim)) continue;
      correct += Number.isFinite(val) ? Math.max(0, Math.min(1, val)) : 0;
      total += 1;
    }
  }
  return { correct, total };
}

// Like evaluateRecentAttempt but LENIENT: an attempt is "acceptable" when every
// enabled dim earned at least PARTIAL_COMPOSITE_CREDIT — i.e. it's clean (1) or
// only short because of a partial-composite pick (naming one valid value of a
// multi-value form). Undo-reattempt fractions (< PARTIAL_COMPOSITE_CREDIT) and
// outright misses (0) are NOT acceptable. Lets getLemmaFormStatus give a form
// whose only shortfall is partial credit a distinct 'partial' status (yellow,
// low shuffle priority) instead of reading it as 'wrong'.
function attemptAllAcceptable(attempt, enabledDims) {
  if (!attempt) return false;
  if (typeof attempt.allDims === 'boolean') return attempt.allDims; // legacy
  const dims = attempt.dims || {};
  for (const [dim, val] of Object.entries(dims)) {
    if (!isDimEnabled(enabledDims, dim)) continue;
    if (!(Number(val) >= PARTIAL_COMPOSITE_CREDIT)) return false;
  }
  return true;
}

// Per-form recent-attempt status for the parsing-review "testable forms"
// list. Returns 'known' / 'right' / 'partial' / 'wrong' / 'uncertain' /
// 'unseen' based on the last-FORM_RECENT_CAP (2) attempts:
//   0/0 → unseen (grey)
//   1/1 clean → right (green)
//   2/2 clean → known (blue) — both recent attempts fully correct; the same
//         threshold isLemmaFormKnown uses for the exclude-known-morphs filter,
//         so a blue dot is exactly a form "skip confident" mode would drop.
//   every attempt acceptable, ≥1 only partially right → partial (yellow) —
//         a multi-value form whose components were named but never in full; the
//         shuffler treats it as correct (low priority) yet it's never excluded.
//   a mix with a genuine miss but something acceptable → uncertain (yellow)
//   all attempts missed → wrong (red)
// Parsing mode doesn't write to the directional progress store, so this is
// the canonical source for "have I attempted this form yet and how did it go."
export function getLemmaFormStatus(stats, lemma, cardId, enabledDims) {
  // Dots reflect the same last-FORM_RECENT_CAP window as the exclude-known
  // filter, so a blue dot is exactly a form "skip confident" would drop —
  // unaffected by the deeper history kept for the confidence breakdown.
  const entry = stats?.byLemma?.[lemma];
  const form = entry?.forms && entry.forms[cardId];
  if (!cardId || !form || !Array.isArray(form.recent) || !form.recent.length) return 'unseen';
  const list = form.recent.slice(-FORM_RECENT_CAP);
  const total = list.length;
  let clean = 0;       // strict: every enabled dim === 1 (the unchanged 2/2 rule)
  let acceptable = 0;  // lenient: clean OR only short by partial-composite credit
  for (const a of list) {
    if (evaluateRecentAttempt(a, enabledDims)) clean += 1;
    if (attemptAllAcceptable(a, enabledDims)) acceptable += 1;
  }
  if (clean === total) return total >= FORM_RECENT_CAP ? 'known' : 'right';
  if (acceptable === total) return 'partial';   // no genuine miss, ≥1 partial pick
  if (clean === 0 && acceptable === 0) return 'wrong';
  return 'uncertain';
}

// Clears one form's per-form recent tally — drops it from the lemma's forms
// map so it reads as 'unseen' again and re-enters the deck when the
// exclude-known-morphs ("skip confident") filter is on. The lemma's rolling
// `attempts` window is intentionally left alone (same scoping as
// resetKnownMorphs, but for a single form). Returns true when something was
// actually cleared.
export function clearLemmaFormRecent(stats, lemma, cardId) {
  if (!stats || !stats.byLemma || !lemma || !cardId) return false;
  const entry = stats.byLemma[lemma];
  if (!entry || !entry.forms || !entry.forms[cardId]) return false;
  delete entry.forms[cardId];
  return true;
}

// Stricter "known" check for the exclude-known-morphs deck filter: the
// form has been correctly parsed in BOTH of its last two attempts. A
// single 1/1 is still green in the UI but isn't excluded here — the user
// has to demonstrate the form twice before parsing mode skips it.
export function isLemmaFormKnown(stats, lemma, cardId, enabledDims) {
  // Strictly the last FORM_RECENT_CAP attempts — the deeper confidence
  // history must not change which forms count as "known" here.
  const { correct, total } = countLemmaFormRecent(stats, lemma, cardId, enabledDims, FORM_RECENT_CAP);
  return total >= FORM_RECENT_CAP && correct >= FORM_RECENT_CAP;
}

// Comprehension-impact weight per parse dimension: how much getting this
// dimension wrong distorts the meaning of the form. Mood and tense reshape a
// clause (is this a command? a past event?) and case assigns who-does-what to
// whom, so they weigh heavily; gender rarely changes comprehension (it mostly
// tracks agreement), so it weighs least. Used to rank parsing review by the
// *kind* of mistakes a form draws, not just the count. Unlisted dims default 1.
export const DIM_COMPREHENSION_WEIGHT = {
  mood: 1.5,
  tense: 1.4,
  case: 1.4,
  voice: 1.3,
  aspect: 1.1,
  person: 1.0,
  number: 0.9,
  gender: 0.6
};

// Importance-weighted recent "wrong steps" magnitude for one form: averages,
// over the form's last `windowSize` attempts, the sum of (1 − credit) × dimWeight
// across every enabled dimension. 0 when every recent attempt was clean; larger
// when a form keeps missing dimensions, and larger still when the missed ones
// are high-impact (a blown mood/tense outweighs a blown gender). Verbs naturally
// score above nouns — they walk more, and weightier, dimensions — so a shaky
// verb outranks a shaky noun, which is what the parsing review order should
// surface. Drives parsingFormPriorityWeight (main.js) for the wrong/uncertain
// tier only; unseen/right/known forms take fixed weights there.
export function weightedRecentMissScore(stats, lemma, cardId, enabledDims, dimWeights = DIM_COMPREHENSION_WEIGHT, windowSize = FORM_RECENT_CAP) {
  if (!cardId) return 0;
  const entry = stats?.byLemma?.[lemma];
  const form = entry?.forms && entry.forms[cardId];
  if (!form || !Array.isArray(form.recent) || !form.recent.length) return 0;
  const list = (Number.isInteger(windowSize) && windowSize > 0)
    ? form.recent.slice(-windowSize)
    : form.recent;
  let sum = 0;
  let n = 0;
  for (const a of list) {
    n += 1;
    if (typeof a.allDims === 'boolean') {
      // Legacy attempt with no per-dim breakdown: a missed whole-parse counts as
      // one generic wrong step, a clean one as none.
      if (!a.allDims) sum += 1;
      continue;
    }
    const dims = a.dims || {};
    for (const [dim, val] of Object.entries(dims)) {
      if (!isDimEnabled(enabledDims, dim)) continue;
      const credit = Number.isFinite(val) ? Math.max(0, Math.min(1, val)) : 0;
      const w = (dimWeights && Number.isFinite(dimWeights[dim])) ? dimWeights[dim] : 1;
      sum += (1 - credit) * w;
    }
  }
  return n ? sum / n : 0;
}

export function getParadigmStepAttemptWindow() {
  return ATTEMPT_WINDOW;
}

// ─── Per-value proficiency breakdown ─────────────────────────────────────
//
// The headline pct and the old bucket bars aggregated across every form, so a
// student strong on present-indicative but weak on aorist-subjunctive read as
// uniformly fine. This breakdown joins each in-scope form's parsed *value*
// (which mood? which tense?) with its saved per-form recent tally, so weakness
// in a specific mood/tense/voice surfaces instead of averaging away.
//
// Derived entirely at read time from `forms` + the card's parse string — no
// new persisted data. `aspect` is intentionally omitted (it's a function of
// tense, already shown). Dimensions appear in this order; a dimension only
// renders when ≥2 of its values exist among the in-scope forms (otherwise
// there's nothing to compare).
const VALUE_BREAKDOWN_DIMS = ['tense', 'mood', 'voice', 'person', 'case', 'number', 'gender'];
const VALUE_ORDER = {
  tense:  ['present', 'future', 'imperfect', 'aorist', 'perfect', 'pluperfect'],
  mood:   ['indicative', 'subjunctive', 'optative', 'imperative', 'infinitive', 'participle'],
  voice:  ['active', 'middle', 'passive', 'middle/passive'],
  person: ['first', 'second', 'third'],
  case:   ['nominative', 'accusative', 'genitive', 'dative', 'vocative'],
  number: ['singular', 'plural'],
  gender: ['masculine', 'feminine', 'neuter']
};
const VALUE_LABEL = {
  person: { first: '1st', second: '2nd', third: '3rd' },
  voice:  { 'middle/passive': 'mid/pass' }
};
function valueDisplayLabel(dim, val) {
  const override = VALUE_LABEL[dim] && VALUE_LABEL[dim][val];
  if (override) return override;
  return val.charAt(0).toUpperCase() + val.slice(1);
}
// Map a parsed dimension value to the atomic breakdown value(s). First/second
// aorist collapse into "aorist". Syncretic case/gender composites
// ("nominative/accusative", "masculine/feminine/neuter") split so the form
// counts toward each member — but a genuine atomic value (e.g. the
// "middle/passive" voice) is kept whole.
function breakdownValuesFor(dim, raw) {
  if (!raw) return [];
  let v = String(raw);
  if (dim === 'tense' && (v === 'first aorist' || v === 'second aorist')) v = 'aorist';
  if (VALUE_ORDER[dim].includes(v)) return [v];
  return v.split('/')
    .map((piece) => (dim === 'tense' && (piece === 'first aorist' || piece === 'second aorist') ? 'aorist' : piece))
    .filter((piece) => VALUE_ORDER[dim].includes(piece));
}

export function createValueBreakdownAcc() {
  const byDim = {};
  for (const dim of VALUE_BREAKDOWN_DIMS) byDim[dim] = {};
  // `totals` drives a paradigm-wide headline: per-dimension credit (≤
  // FORM_HISTORY_CAP attempts per form, each dimension scored on its own)
  // summed across every in-scope form, plus seen/in-scope form coverage. This
  // is the deeper history, not the 2/2 known window. This is what the per-
  // paradigm and "All paradigms" % report — a dimension-level proficiency that
  // scales with the paradigm and stays consistent with the per-value bars.
  return { byDim, totals: { correct: 0, total: 0, seen: 0, scope: 0 } };
}

// Fold one lemma's in-scope cards into the accumulator. `cards` come from the
// same focused-paradigm pool the deck uses (chapter-gated), so coverage counts
// match what's actually drillable. Call once per lemma, reusing the acc, to
// build a cross-paradigm aggregate.
export function accumulateValueBreakdown(acc, stats, lemma, cards, enabledDims) {
  if (!acc || !Array.isArray(cards)) return acc;
  for (const card of cards) {
    if (!card || !card.id) continue;
    const dims = parseAnswerDimensions(card.parsedAnswer || card.answer);
    const status = getLemmaFormStatus(stats, lemma, card.id, enabledDims);
    // Per-dimension accuracy: each dimension scores on its own (1 clean / 0.5
    // reattempted / 0 missed), so a form parsed 4-of-5-dims-right counts 0.8,
    // not the whole-parse 0. The per-value bars and headline % report this
    // dimension-level proficiency. The dots (status, above) stay strict-binary,
    // as does the 2/2 known check.
    const { correct, total } = countLemmaFormDimCredit(stats, lemma, card.id, enabledDims);
    // Once-per-form paradigm-wide tally (recent attempts + coverage).
    acc.totals.scope += 1;
    if (status !== 'unseen') acc.totals.seen += 1;
    acc.totals.correct += correct;
    acc.totals.total += total;
    for (const dim of VALUE_BREAKDOWN_DIMS) {
      if (!isDimEnabled(enabledDims, dim)) continue;
      for (const val of breakdownValuesFor(dim, dims[dim])) {
        const bag = acc.byDim[dim];
        if (!bag[val]) bag[val] = { forms: 0, seenForms: 0, correct: 0, total: 0 };
        const e = bag[val];
        e.forms += 1;
        if (status !== 'unseen') e.seenForms += 1;
        e.correct += correct;
        e.total += total;
      }
    }
  }
  return acc;
}

// Collapse the accumulator into render-ready groups (canonical value order),
// the single weakest seen value across every dimension — the "drill this next"
// pointer — and the paradigm-wide `totals` (headline % + form coverage). `pct`
// is null for a value with no recent attempts (rendered as an unseen track,
// surfacing coverage gaps).
export function finalizeValueBreakdown(acc, options = {}) {
  const minValues = Number.isFinite(options.minValues) ? options.minValues : 2;
  const groups = [];
  let weakest = null;
  const emptyTotals = { correct: 0, total: 0, seen: 0, scope: 0, pct: null };
  if (!acc || !acc.byDim) return { groups, weakest, totals: emptyTotals };
  for (const dim of VALUE_BREAKDOWN_DIMS) {
    const bag = acc.byDim[dim];
    const present = VALUE_ORDER[dim].filter((v) => bag[v]);
    if (present.length < minValues) continue;
    const rows = present.map((v) => {
      const e = bag[v];
      const pct = e.total ? Math.round(100 * e.correct / e.total) : null;
      if (pct != null && e.seenForms > 0 && (!weakest || pct < weakest.pct)) {
        weakest = { dim, value: v, label: valueDisplayLabel(dim, v), pct };
      }
      return {
        value: v,
        label: valueDisplayLabel(dim, v),
        pct,
        forms: e.forms,
        seenForms: e.seenForms
      };
    });
    groups.push({ dim, label: DIM_LABEL[dim] || dim, rows });
  }
  const t = acc.totals || emptyTotals;
  const totals = {
    correct: t.correct,
    total: t.total,
    seen: t.seen,
    scope: t.scope,
    pct: t.total ? Math.round(100 * t.correct / t.total) : null
  };
  return { groups, weakest, totals };
}

// Convenience: full breakdown for a single lemma in one call.
export function summarizeLemmaValueBreakdown(stats, lemma, cards, enabledDims, options) {
  const acc = createValueBreakdownAcc();
  accumulateValueBreakdown(acc, stats, lemma, cards, enabledDims);
  return finalizeValueBreakdown(acc, options);
}
